/**
 * Full Thrust: Project Continuum — Faster Than Light (section 11).
 *
 * Section 11 is not a movement rule. Nothing in it moves a ship anywhere
 * useful: the whole section is the price of arriving or leaving in the wrong
 * place, and every mechanic in it is the same proximity test with the same
 * radius. *"The forces generated by FTL Drive units are very powerful, and
 * result in spatial distortions that can be highly dangerous in close
 * proximity to any other mass, including other ships"* (11.1) — 6 MU of
 * "close proximity", measured with `distance`, is most of what this module
 * does.
 *
 * The one thing a reader must not carry from one half of the section to the
 * other is that **the exit table and the entry table are different tables**.
 * On exit (11.4) a 1 is a damp squib and a 5 or 6 kills the ship and everything
 * around it; on entry (11.5) a 1 is a scratch, a 6 is up to 36 points, and the
 * ships nearby are hurt *every time the roll is made* rather than only on a
 * disaster. Getting those two the wrong way round is the failure this module is
 * shaped to prevent, which is why `resolveFtlExit` and `resolveFtlEntry` share
 * only their proximity helper and nothing else.
 *
 * Damage is *reported*, never applied — how these points land is `combat.ts`'s
 * business (4.8, 4.9) and the threshold checks they open are `threshold.ts`'s
 * (4.11) — exactly as in `gunboats.ts`. What this module does add to the report
 * is that FTL damage *"cannot be absorbed by screens or armor"* (11.5), which
 * the caller has no other way of knowing.
 *
 * Driven by, not replacing, what `game.ts` already records: `ShipState.
 * ftlTransit` is the per-turn declaration of 11.4's movement order, and
 * `shipMovementRank` already puts a transiting ship last in phase 5, which is
 * 11.4's *"ships exiting by FTL are moved after all other ships"*.
 *
 * Every quotation is from *Full Thrust: Project Continuum* v1.1.4, sections
 * 11.1 – 11.11; the prose is in `docs/rules/ftl.md`, which is what this file is
 * checked against, and the fifteen readings marked **[reading]** below are
 * collected in a table there.
 */

import { d6, rollD6, type Rng } from './dice'
import { arcTo, distance, moveShip } from './geometry'
import type { Course, FtlKind, Point, ShipDesign } from './types'

const EPSILON = 1e-9

// ---------------------------------------------------------------------------
// The shared vocabulary of section 11
// ---------------------------------------------------------------------------

/**
 * *"the danger radius is 6 MU around the actual point of appearance"* (11.5),
 * and the same 6 MU *"of the actual point of FTL exit"* (11.4). One radius for
 * the whole section.
 */
export const FTL_DANGER_RADIUS = 6

/** *"All other ships or starbases within 6 MU immediately suffer 2D6 damage"* (11.4, 11.5). */
export const BYSTANDER_DAMAGE_DICE = 2

/** Points on the course gauge a D12 scatter reads onto (3.1, 11.5). */
export const COURSE_GAUGE_POINTS = 12

/**
 * How a ship is using its FTL drive this turn. The same three strings as
 * `game.ts`'s `FtlTransit`, so `ship.ftlTransit` passes straight into this
 * module; it is restated here rather than imported because `ftl.ts` sits below
 * `game.ts` in the dependency order.
 */
export type FtlTransitPhase = 'none' | 'entering' | 'exiting'

/**
 * A ship-sized or larger object, for the proximity tests of 11.4 and 11.5.
 * *"any other ship-sized or larger object, but not fighter groups or missile
 * salvos"* — the exclusion is why fighters and missiles are a separate list.
 */
export interface FtlObject {
  id: string
  position: Point
}

/**
 * A hull riding another ship's drive field: *"Non-FTL ships being carried by a
 * tug or tender or battleriders carried by a Mothership"* (11.4).
 */
export interface FtlPassenger {
  id: string
}

/** What a proximity roll did to one hull. Damage is reported, never applied. */
export interface FtlProximityDamage {
  id: string
  /** The dice as rolled, for the log. */
  dice: number[]
  damage: number
  destroyed: boolean
}

/** The rectangle the game is played on, for 11.5's "appears off table" clause. */
export interface TableBounds {
  minX: number
  minY: number
  maxX: number
  maxY: number
}

/**
 * A d12 (11.5): *"roll a D12 to give a direction on the course gauge"*.
 *
 * `dice.ts` opens by saying Full Thrust is *"a pure d6 game: every roll in the
 * book is one or more plain six-sided dice"*, and it is right everywhere except
 * here — 11.5's scatter direction is the one non-d6 in the rulebook. It lives
 * in this module rather than in `dice.ts` because this is the only rule that
 * uses it.
 */
export function d12(rng: Rng): number {
  return rng.int(COURSE_GAUGE_POINTS) + 1
}

/** Whether a fit is the precise kind of drive 11.3 describes. */
export function isAdvancedFtl(ftl: FtlKind): boolean {
  return ftl === 'advanced'
}

function sum(values: readonly number[]): number {
  return values.reduce((total, value) => total + value, 0)
}

function within(centre: Point, objects: readonly FtlObject[]): FtlObject[] {
  return objects.filter((object) => distance(centre, object.position) <= FTL_DANGER_RADIUS + EPSILON)
}

/**
 * The blast around a transition point, shared by 11.4 and 11.5 because both
 * word it identically: 2D6 on every other ship in the radius, and every fighter
 * group or missile marker in it destroyed outright.
 *
 * The 2D6 is rolled per target rather than once for the lot, as every damage
 * expression in Full Thrust is; the report keeps each target's dice so a caller
 * can log what happened to whom.
 */
function proximityCasualties(
  centre: Point,
  nearby: readonly FtlObject[],
  lightCraft: readonly FtlObject[],
  rng: Rng,
): { bystanders: FtlProximityDamage[]; lightCraftDestroyed: string[] } {
  const bystanders = within(centre, nearby).map((object) => {
    const dice = rollD6(BYSTANDER_DAMAGE_DICE, rng)
    return { id: object.id, dice, damage: sum(dice), destroyed: false }
  })
  return {
    bystanders,
    lightCraftDestroyed: within(centre, lightCraft).map((object) => object.id),
  }
}

// ---------------------------------------------------------------------------
// 11.2 Hyper limit
// ---------------------------------------------------------------------------

/**
 * A zone within which FTL is impossible (11.2): *"decent sized planets or the
 * local sun have a 'hyper limit' distance within which FTL travel is not
 * possible"*. A scenario object — a centre and a radius — not a ship property.
 */
export interface HyperLimitZone {
  id: string
  centre: Point
  /** Radius in MU (2.1). */
  radius: number
  label?: string
}

/**
 * The scenario's hyper-limit setting (11.2). `permittedInsideLimit` is the
 * book's own escape hatch: *"FTL entry or exit is only permitted by player
 * agreement or scenario design"*.
 */
export interface HyperLimitRules {
  zones: readonly HyperLimitZone[]
  permittedInsideLimit: boolean
}

/** The zone a point lies inside, or null (11.2). The first match wins. */
export function hyperLimitAt(point: Point, rules: HyperLimitRules | undefined): HyperLimitZone | null {
  if (!rules) return null
  return (
    rules.zones.find((zone) => distance(point, zone.centre) <= zone.radius + EPSILON) ?? null
  )
}

export interface FtlPermission {
  permitted: boolean
  zone: HyperLimitZone | null
  reason: string
}

/**
 * May a transition be attempted here (11.2)?
 *
 * **[reading]** A jump ordered inside a hyper limit is *refused*, not resolved.
 * 11.2 says FTL *"is only permitted by player agreement or scenario design"* —
 * a permission, with no penalty, roll or misjump printed for trying anyway — so
 * the order is illegal in the way an out-of-range gunboat attack is illegal.
 * The alternative, resolving it as an automatic misjump or an automatic loss,
 * would invent a number the book does not have; the mechanism the book *does*
 * offer is `permittedInsideLimit`, which a scenario sets.
 */
export function ftlPermittedAt(point: Point, rules?: HyperLimitRules): FtlPermission {
  const zone = hyperLimitAt(point, rules)
  if (zone === null || rules?.permittedInsideLimit === true) {
    return { permitted: true, zone, reason: '' }
  }
  return {
    permitted: false,
    zone,
    reason: `inside the hyper limit of ${zone.label ?? zone.id}; FTL is permitted there only by player agreement or scenario design (11.2)`,
  }
}

// ---------------------------------------------------------------------------
// 11.4 FTL exit
// ---------------------------------------------------------------------------

/**
 * Where a departing ship is in 11.4's two-turn sequence. `warming-up` is the
 * turn the order is written; `jumping` is *"the following turn"*, on which the
 * ship half-moves and vanishes.
 */
export type FtlExitStage = 'warming-up' | 'jumping' | 'gone'

/**
 * Which turn of the exit a ship is on (11.4).
 *
 * `game.ts` clears `ftlTransit` in `onBeginTurn`, correctly — both 11.4's
 * movement order and 11.5's announcement are written fresh each turn — so the
 * turn the drive was first declared has no home on `ShipState` and is passed
 * in here as a value.
 */
export function ftlExitStage(warmupTurn: number, turn: number): FtlExitStage {
  if (turn <= warmupTurn) return 'warming-up'
  if (turn === warmupTurn + 1) return 'jumping'
  return 'gone'
}

/**
 * What a departing ship may still do (11.4): *"The ship may not apply any
 * thrust in that move, nor may it use any offensive weaponry or ADFC. (PDS and
 * screens may continue to be used.)"*
 */
export interface FtlExitRestrictions {
  stage: FtlExitStage
  mayThrust: boolean
  mayFireOffensiveWeapons: boolean
  mayUseAdfc: boolean
  mayUsePds: boolean
  mayUseScreens: boolean
  /** False once the ship has half-moved out of normal space in phase 5. */
  onTableAfterMovement: boolean
  note: string
}

/**
 * The warm-up turn's restrictions, and the jump turn's (11.4).
 *
 * **[reading]** The jump turn is at least as restricted as the warm-up turn,
 * PDS included. 11.4 spells the restrictions out for the warm-up turn and says
 * nothing about the following one — it does not need to, because the jump
 * happens in phase 5 and every phase that could use a weapon, an ADFC or a PDS
 * (9, 10, 11) comes after it. Reporting all five as false with
 * `onTableAfterMovement: false` says why. The alternative, carrying the warm-up
 * permissions forward verbatim, would let a ship that vanished in phase 5 shoot
 * down a missile in phase 9.
 */
export function ftlExitRestrictions(stage: FtlExitStage): FtlExitRestrictions {
  if (stage === 'warming-up') {
    return {
      stage,
      mayThrust: false,
      mayFireOffensiveWeapons: false,
      mayUseAdfc: false,
      mayUsePds: true,
      mayUseScreens: true,
      onTableAfterMovement: true,
      note: 'FTL drive warming up: no thrust, no offensive weapons, no ADFC; PDS and screens may continue to be used (11.4)',
    }
  }
  return {
    stage,
    mayThrust: false,
    mayFireOffensiveWeapons: false,
    mayUseAdfc: false,
    mayUsePds: false,
    mayUseScreens: false,
    onTableAfterMovement: false,
    note:
      stage === 'jumping'
        ? 'half move on the present course in phase 5, then off the table before any firing phase (11.4)'
        : 'the ship has gone into FTL space and may not return to play this battle (11.4)',
  }
}

/**
 * The jump turn's move (11.4): *"the ship moves half its current velocity on
 * its present course, then disappears from the playing area"*.
 *
 * **[reading]** Half rounds down. 11.4 gives no rounding rule; 3.4, the
 * engine's only other place a velocity is halved, rounds the first leg down and
 * `moveShip` implements that as `Math.floor(velocity / 2)`. Using the same
 * floor means a velocity-9 ship travels 4 MU whichever code path measures it.
 * Rounding up would make the two halves of the engine disagree about what half
 * of nine is.
 */
export function ftlExitMove(
  from: Point,
  course: Course,
  velocity: number,
): { position: Point; distance: number } {
  const half = Math.floor(Math.max(0, velocity) / 2)
  return { position: moveShip(from, course, half, 0).position, distance: half }
}

/** The four ways 11.4's D6 can land, plus 11.2's refusal. */
export type FtlExitOutcome = 'refused' | 'clear' | 'drive-failed' | 'damaged' | 'catastrophe'

export interface FtlExitContext {
  /** *"the point that the ship disappears from the table"* — the end of the half move. */
  exitPoint: Point
  /** 11.3: an Advanced FTL Drive leaves *"without risk of collisions or scattering"*. */
  advancedDrive?: boolean
  /** Ship-sized or larger objects, which are what trigger the roll (11.4). */
  nearby?: readonly FtlObject[]
  /** Fighter groups and missile markers: casualties, but never triggers (11.4). */
  lightCraft?: readonly FtlObject[]
  /** Non-FTL ships under tow and battleriders aboard (11.4). */
  passengers?: readonly FtlPassenger[]
  hyperLimit?: HyperLimitRules
}

export interface FtlExitReport {
  outcome: FtlExitOutcome
  /** False when nothing was close enough to make the roll necessary. */
  rolled: boolean
  roll: number | null
  selfDice: number[]
  selfDamage: number
  selfDestroyed: boolean
  /** The ship left the table. */
  jumped: boolean
  /** On a 1, *"The ship remains in normal space at its present course and velocity"*. */
  remainsInNormalSpace: boolean
  /** *"Once a ship has left the table under FTL Drive, it may not return"* (11.4). */
  permanentlyGone: boolean
  /** *"Any threshold point checks would be made 'off table'"* (11.4). */
  thresholdChecksOffTable: boolean
  /** *"Damage from FTL entry or exit cannot be absorbed by screens or armor"* (11.5). */
  bypassesScreensAndArmour: boolean
  bystanders: FtlProximityDamage[]
  lightCraftDestroyed: string[]
  passengers: FtlProximityDamage[]
  note: string
}

function emptyExitReport(outcome: FtlExitOutcome, note: string): FtlExitReport {
  return {
    outcome,
    rolled: false,
    roll: null,
    selfDice: [],
    selfDamage: 0,
    selfDestroyed: false,
    jumped: false,
    remainsInNormalSpace: true,
    permanentlyGone: false,
    thresholdChecksOffTable: false,
    bypassesScreensAndArmour: true,
    bystanders: [],
    lightCraftDestroyed: [],
    passengers: [],
    note,
  }
}

/**
 * Resolve a ship going into FTL space (11.4).
 *
 * The roll only happens if *"any other ship-sized or larger object, but not
 * fighter groups or missile salvos, are within 6 MU of the actual point of FTL
 * exit"*. The trigger list and the casualty list are deliberately different:
 * a fighter group 3 MU away does not cause the roll, and dies if the roll comes
 * up 5 or 6. Distance is measured from the end of the half move, which is where
 * the ship actually disappears.
 *
 *   1     the drive fails; the ship stays, course and velocity unchanged
 *   2–4   1D6 on the ship, which then jumps unless the damage killed it
 *   5–6   the ship is destroyed, 2D6 on every other ship in the radius, and
 *         every fighter group and missile marker in it is destroyed
 *
 * **[reading]** An Advanced FTL Drive skips this roll. 11.3 says such ships
 * *"enter or leave space very precisely without risk of collisions or
 * scattering"*; scattering is 11.5's D12/D6, so "collisions" can only be this.
 * The alternative — waiving the scatter alone, which is the literal text of
 * 11.5 — would leave an Advanced drive placing a ship on an exact coordinate
 * and then rolling to see whether it explodes there.
 */
export function resolveFtlExit(context: FtlExitContext, rng: Rng): FtlExitReport {
  const permission = ftlPermittedAt(context.exitPoint, context.hyperLimit)
  if (!permission.permitted) return emptyExitReport('refused', permission.reason)

  const nearby = context.nearby ?? []
  const lightCraft = context.lightCraft ?? []
  const passengers = context.passengers ?? []

  const triggers = within(context.exitPoint, nearby)
  if (context.advancedDrive === true || triggers.length === 0) {
    const note =
      context.advancedDrive === true
        ? 'Advanced FTL Drive: leaves without risk of collisions or scattering (11.3)'
        : 'nothing ship-sized within 6 MU of the exit point (11.4)'
    return { ...emptyExitReport('clear', note), jumped: true, remainsInNormalSpace: false, permanentlyGone: true }
  }

  const roll = d6(rng)

  if (roll === 1) {
    return {
      ...emptyExitReport('drive-failed', 'the FTL Drive fails to engage; the ship completes the current movement (11.4)'),
      rolled: true,
      roll,
    }
  }

  if (roll <= 4) {
    const selfDice = rollD6(1, rng)
    const selfDamage = sum(selfDice)
    // "Unless the ship is actually destroyed by this damage, it completes its
    // FTL transition safely" — whether it *is* destroyed is the caller's
    // arithmetic against a hull this module never sees, so the report says the
    // damage and leaves the verdict open.
    return {
      ...emptyExitReport('damaged', 'the ship suffers 1D6 and completes its transition unless the damage kills it (11.4)'),
      rolled: true,
      roll,
      selfDice,
      selfDamage,
      jumped: true,
      remainsInNormalSpace: false,
      permanentlyGone: true,
      thresholdChecksOffTable: true,
      // **[reading]** Each passenger rolls its own 1D6. 11.4's clause reads
      // "also suffer 1D6 damage or are destroyed depending on the FTL entry
      // roll": "1D6 or destroyed" are the *exit* table's two outcomes and the
      // entry table has neither, so the clause is the exit clause despite the
      // word "entry"; and "1D6" is a fresh dice expression rather than a
      // reference to what the carrier took. The alternative, every passenger
      // taking the carrier's number, would make a tender full of System
      // Defense Ships a single die roll.
      passengers: passengers.map((passenger) => {
        const dice = rollD6(1, rng)
        return { id: passenger.id, dice, damage: sum(dice), destroyed: false }
      }),
    }
  }

  const casualties = proximityCasualties(context.exitPoint, nearby, lightCraft, rng)
  return {
    ...emptyExitReport('catastrophe', 'the ship is completely destroyed; 2D6 on every ship within 6 MU and every fighter group or missile marker in it is destroyed (11.4)'),
    rolled: true,
    roll,
    selfDestroyed: true,
    remainsInNormalSpace: false,
    bystanders: casualties.bystanders,
    lightCraftDestroyed: casualties.lightCraftDestroyed,
    passengers: passengers.map((passenger) => ({
      id: passenger.id,
      dice: [],
      damage: 0,
      destroyed: true,
    })),
  }
}

// ---------------------------------------------------------------------------
// 11.5 FTL entry
// ---------------------------------------------------------------------------

/**
 * The declaration made at the start of the game (11.5): *"the number of the
 * game turn in which they will enter, plus a specified point of entry on the
 * table … the starting course and velocity of the ship after its emergence"*.
 */
export interface FtlEntryPlan {
  shipId: string
  turn: number
  entryPoint: Point
  course: Course
  velocity: number
}

export interface FtlScatterResult {
  /** The D12 on the course gauge, or null for an Advanced drive (11.3, 11.5). */
  directionRoll: number | null
  /** The scatter direction as a clock course (3.1). */
  direction: Course | null
  distanceRoll: number | null
  /** The optional rule's second die, rolled only after a 6 (11.5). */
  secondDistanceRoll: number | null
  /** MU of error actually applied. */
  distance: number
  from: Point
  to: Point
  scattered: boolean
  /** *"deemed unable to enter the table during the battle"* (11.5). */
  offTable: boolean
  note: string
}

function insideBounds(point: Point, bounds: TableBounds): boolean {
  return (
    point.x >= bounds.minX - EPSILON &&
    point.x <= bounds.maxX + EPSILON &&
    point.y >= bounds.minY - EPSILON &&
    point.y <= bounds.maxY + EPSILON
  )
}

/**
 * The entry error (11.5): *"roll a D12 to give a direction on the course gauge
 * and a D6 for distance. The marker is then moved in the direction rolled to a
 * distance in MU equal to the D6 roll."*
 *
 * The D12 reads straight onto the clock face because "the course gauge" is
 * 3.1's twelve-point gauge the engine already stores courses on, and the
 * direction is independent of the ship's own course — a 12 scatters up the
 * table whichever way the ship is pointing.
 *
 * The optional rule multiplies rather than adds: *"if the distance D6 roll is a
 * 6, then roll a second D6 and multiply the result by the original roll of 6"*,
 * so the error is 6, 12, 18, 24, 30 or 36 MU, never 6 plus something.
 *
 * **[reading]** The *"appears off table"* clause is checked for any scatter
 * when `bounds` are supplied, not only under the optional rule. Grammatically
 * "this" means the massive error, but a plain 6 MU scatter off a corner entry
 * point puts a marker over the edge just as effectively and the book gives no
 * other answer for one that does. The alternative — off-table markers being
 * legal under the base rule — needs a rule for playing a ship that is not on
 * the table, which the book does not have. Supply no bounds and nothing is
 * checked.
 */
export function rollFtlEntryScatter(
  from: Point,
  rng: Rng,
  opts: { advancedDrive?: boolean; massiveError?: boolean; bounds?: TableBounds | null } = {},
): FtlScatterResult {
  if (opts.advancedDrive === true) {
    return {
      directionRoll: null,
      direction: null,
      distanceRoll: null,
      secondDistanceRoll: null,
      distance: 0,
      from,
      to: { ...from },
      scattered: false,
      offTable: false,
      note: 'Advanced FTL Drive: enters precisely, without scattering (11.3)',
    }
  }

  const directionRoll = d12(rng)
  const direction = directionRoll as Course
  const distanceRoll = d6(rng)
  let secondDistanceRoll: number | null = null
  let error = distanceRoll
  if (opts.massiveError === true && distanceRoll === 6) {
    // "a potentially massive error (up to 36 MU)" — the second die multiplied
    // by six, so a 6 and a 6 puts the ship most of a table away (11.5).
    secondDistanceRoll = d6(rng)
    error = 6 * secondDistanceRoll
  }

  const to = moveShip(from, direction, error, 0).position
  const offTable = opts.bounds ? !insideBounds(to, opts.bounds) : false
  return {
    directionRoll,
    direction,
    distanceRoll,
    secondDistanceRoll,
    distance: error,
    from,
    to,
    scattered: error > 0,
    offTable,
    note: offTable ? 'scattered off the table; unable to enter during this battle (11.5)' : '',
  }
}

/** The entry danger roll's report (11.5). No destruction result: the table has none. */
export interface FtlEntryDangerReport {
  rolled: boolean
  roll: number | null
  /** The second die of a 6, which is multiplied by 6 (11.5). */
  secondRoll: number | null
  selfDamage: number
  bystanders: FtlProximityDamage[]
  lightCraftDestroyed: string[]
  /** *"Damage from FTL entry or exit cannot be absorbed by screens or armor"* (11.5). */
  bypassesScreensAndArmour: boolean
  /** *"If sufficient damage is inflicted to reach a threshold point … roll threshold point checks as usual"*. */
  thresholdChecksOnTable: boolean
  note: string
}

export interface FtlEntryContext {
  advancedDrive?: boolean
  /** The optional massive-error rule of 11.5. */
  massiveError?: boolean
  bounds?: TableBounds | null
  nearby?: readonly FtlObject[]
  lightCraft?: readonly FtlObject[]
  /**
   * *"Ships carried by a tug or tender or battleriders carried by a Mothership,
   * or FTL-capable fighters screening a ship move the same distance and
   * direction as their ship"* (11.5) — the same displacement, not the same
   * destination, so a formation arrives as a formation.
   */
  carried?: readonly FtlObject[]
  hyperLimit?: HyperLimitRules
}

export interface FtlEntryResult {
  plan: FtlEntryPlan
  scatter: FtlScatterResult
  /** Where the ship actually appears, or null if it never does. */
  arrival: Point | null
  entered: boolean
  /** Scattered off the table: *"unable to enter the table during the battle"* (11.5). */
  barredFromBattle: boolean
  refusal: string
  danger: FtlEntryDangerReport | null
  /** *"its current velocity being applied from the start of the next"* turn (11.5). */
  velocityAppliesFromTurn: number
  carried: Array<{ id: string; from: Point; to: Point }>
}

/**
 * Resolve a ship dropping out of FTL onto the table (11.5).
 *
 * Scatter first, then the danger roll — and the danger roll is measured from
 * *"the actual point of appearance"*, which is the scattered point, not the
 * point the player wrote down. Two ships entering side by side can therefore
 * scatter apart into safety or scatter into one another.
 *
 * The table, once the roll is triggered:
 *
 *   1–5   the arriving ship takes damage equal to the die
 *   6     roll again and multiply by 6: 6, 12, 18, 24, 30 or 36 points
 *
 * and then, *unconditionally* — the clause is not indented under either bullet
 * — *"Any other ship within 6 MU takes 2D6 damage, and any fighter group or
 * missile marker is destroyed."* A ship that arrives beside a starbase and
 * rolls a 1 takes one point and still puts 2D6 into the starbase. That is the
 * opposite of 11.4, where the bystanders are only hurt on a 5 or 6, and it is
 * the single easiest thing in section 11 to get backwards.
 *
 * *"The FTL entry is the ship's movement for that turn"*, so the caller must
 * not also move the ship; its velocity starts applying next turn.
 */
export function resolveFtlEntry(
  plan: FtlEntryPlan,
  context: FtlEntryContext,
  rng: Rng,
): FtlEntryResult {
  const base: Omit<FtlEntryResult, 'scatter'> = {
    plan,
    arrival: null,
    entered: false,
    barredFromBattle: false,
    refusal: '',
    danger: null,
    velocityAppliesFromTurn: plan.turn + 1,
    carried: [],
  }

  const permission = ftlPermittedAt(plan.entryPoint, context.hyperLimit)
  if (!permission.permitted) {
    return {
      ...base,
      refusal: permission.reason,
      scatter: {
        directionRoll: null,
        direction: null,
        distanceRoll: null,
        secondDistanceRoll: null,
        distance: 0,
        from: plan.entryPoint,
        to: { ...plan.entryPoint },
        scattered: false,
        offTable: false,
        note: permission.reason,
      },
    }
  }

  const scatter = rollFtlEntryScatter(plan.entryPoint, rng, {
    advancedDrive: context.advancedDrive,
    massiveError: context.massiveError,
    bounds: context.bounds,
  })

  if (scatter.offTable) {
    return { ...base, scatter, barredFromBattle: true }
  }

  const arrival = scatter.to
  const dx = arrival.x - plan.entryPoint.x
  const dy = arrival.y - plan.entryPoint.y
  const carried = (context.carried ?? []).map((rider) => ({
    id: rider.id,
    from: rider.position,
    to: { x: rider.position.x + dx, y: rider.position.y + dy },
  }))

  return {
    ...base,
    scatter,
    arrival,
    entered: true,
    carried,
    danger: resolveFtlEntryDanger(arrival, context, rng),
  }
}

/**
 * The arrival danger roll on its own (11.5), for a caller that has already
 * placed the ship — a gate arrival that still wants the check, or a scenario
 * that puts a ship down by hand.
 */
export function resolveFtlEntryDanger(
  arrival: Point,
  context: FtlEntryContext,
  rng: Rng,
): FtlEntryDangerReport {
  const nearby = context.nearby ?? []
  const lightCraft = context.lightCraft ?? []

  const clear: FtlEntryDangerReport = {
    rolled: false,
    roll: null,
    secondRoll: null,
    selfDamage: 0,
    bystanders: [],
    lightCraftDestroyed: [],
    bypassesScreensAndArmour: true,
    thresholdChecksOnTable: false,
    note: '',
  }

  // **[reading]** 11.3's Advanced drive is free of "collisions" as well as
  // scattering; see `resolveFtlExit`.
  if (context.advancedDrive === true) {
    return { ...clear, note: 'Advanced FTL Drive: enters without risk of collisions (11.3)' }
  }
  if (within(arrival, nearby).length === 0) {
    return { ...clear, note: 'nothing ship-sized within 6 MU of the point of appearance (11.5)' }
  }

  const roll = d6(rng)
  let secondRoll: number | null = null
  let selfDamage = roll
  if (roll === 6) {
    secondRoll = d6(rng)
    selfDamage = 6 * secondRoll
  }

  // Unconditional: the bystander clause sits below both bullets, not inside
  // either, so it fires however well the arriving ship rolled.
  const casualties = proximityCasualties(arrival, nearby, lightCraft, rng)
  return {
    rolled: true,
    roll,
    secondRoll,
    selfDamage,
    bystanders: casualties.bystanders,
    lightCraftDestroyed: casualties.lightCraftDestroyed,
    bypassesScreensAndArmour: true,
    thresholdChecksOnTable: true,
    note: 'arrived within 6 MU of another body (11.5)',
  }
}

// ---------------------------------------------------------------------------
// 11.6 FTL tugs and tenders
// ---------------------------------------------------------------------------

/** *"every 1.5 mass used for hangar bay space provides capacity for 1 mass of carried ship(s)"* (11.6). */
export const TENDER_BAY_MASS_PER_CARRIED_MASS = 1.5

/** *"The points cost of such space is the same as for other hangar facilities, 3 × the total mass used"* (11.6). */
export const TENDER_BAY_POINTS_PER_MASS = 3

/** *"a FTL Drive equal to 10% of their mass just to provide their own FTL capability"* (11.6). */
export const TUG_OWN_FTL_FRACTION = 0.1

/** *"for every 1 additional FTL Drive mass they can tow an additional 5 transfer mass"* (11.6). */
export const TUG_TRANSFER_MASS_PER_SPARE_DRIVE_MASS = 5

/**
 * Bay mass needed to carry `carriedMass` of shipping (11.6). Not rounded: the
 * rate is 1.5, the mass of a bay is what the construction table records, and
 * imposing a rounding rule section 11 does not state would put this module out
 * of step with section 14.
 */
export function tenderBayMassFor(carriedMass: number): number {
  return Math.max(0, carriedMass) * TENDER_BAY_MASS_PER_CARRIED_MASS
}

/** What a bay of `bayMass` can carry — *"30 mass … could carry a mass 20 ship"* (11.6). */
export function tenderCapacityFor(bayMass: number): number {
  return Math.max(0, bayMass) / TENDER_BAY_MASS_PER_CARRIED_MASS
}

export function tenderBayPoints(bayMass: number): number {
  return Math.max(0, bayMass) * TENDER_BAY_POINTS_PER_MASS
}

/**
 * A tug's own FTL drive (11.6), before any towing capacity.
 *
 * **[reading]** Rounds up, as does `tugSpareDriveMassFor`. The book rounds the
 * spare capacity up in its own worked example (108/5 = 21.6 becomes 22) and its
 * own-drive example, 10% of 60, is exact and settles nothing. A tug is either
 * strong enough for the tow or it is not, and the alternative — fractional
 * drive mass — would print a mass-10.8 FTL drive on an SSD.
 */
export function tugOwnDriveMass(tugMass: number): number {
  return Math.ceil(Math.max(0, tugMass) * TUG_OWN_FTL_FRACTION)
}

/** Spare drive mass to tow `transferMass` — *"to tow a ship of mass 108 … mass 22"* (11.6). */
export function tugSpareDriveMassFor(transferMass: number): number {
  return Math.ceil(Math.max(0, transferMass) / TUG_TRANSFER_MASS_PER_SPARE_DRIVE_MASS)
}

/**
 * The whole drive package (11.6): *"If the tug itself was a mass 60 ship, it
 * would need its own mass 6 FTL Drive plus the additional 22 – so it would have
 * to devote a total of 28 mass to its FTL Drive package."*
 */
export function tugDriveMass(tugMass: number, transferMass: number): number {
  return tugOwnDriveMass(tugMass) + tugSpareDriveMassFor(transferMass)
}

/** What a given drive package can actually tow — the inverse of `tugDriveMass`. */
export function tugTransferMass(tugMass: number, driveMass: number): number {
  const spare = Math.max(0, driveMass - tugOwnDriveMass(tugMass))
  return spare * TUG_TRANSFER_MASS_PER_SPARE_DRIVE_MASS
}

/** A tug in a towing job (11.6). Grade matters: only Advanced tugs may combine. */
export interface TugFit {
  id: string
  transferMass: number
  advanced: boolean
}

export interface TowLoad {
  id: string
  mass: number
}

export interface TowCheck {
  legal: boolean
  capacity: number
  load: number
  problems: string[]
}

/**
 * May these tugs move this load (11.6)?
 *
 * Two rules, and the second is the one that surprises: *"Tugs with standard FTL
 * Drives can haul any number of ships, provided that the total mass does not
 * exceed the transfer mass capacity of the drive. Tugs with Advanced FTL Drives
 * can also combine to haul ships larger than any individual ship capacity."*
 *
 * Capacity is additive across tugs only where the tugs are Advanced, which is
 * exactly the book's example: *"A crippled battleship with mass 120 can be
 * hauled off table by one tug with a standard FTL Drive with a transfer mass of
 * 120 or more, or by two tugs with Advanced FTL Drives of transfer mass 60
 * each."* Two *standard* tugs of 60 cannot move it between them.
 *
 * Which tug takes which ship is not decided here — 11.6 states no assignment
 * rule — only the two limits it does state.
 */
export function tugTowCheck(tugs: readonly TugFit[], load: readonly TowLoad[]): TowCheck {
  const capacity = sum(tugs.map((tug) => Math.max(0, tug.transferMass)))
  const advancedCapacity = sum(
    tugs.filter((tug) => tug.advanced).map((tug) => Math.max(0, tug.transferMass)),
  )
  const largestSingle = tugs.reduce((best, tug) => Math.max(best, tug.transferMass), 0)
  const total = sum(load.map((ship) => Math.max(0, ship.mass)))
  const problems: string[] = []

  if (tugs.length === 0 && load.length > 0) problems.push('no tug to haul with (11.6)')
  if (total > capacity + EPSILON) {
    problems.push(`load of ${total} mass exceeds the tugs' combined transfer mass of ${capacity} (11.6)`)
  }
  for (const ship of load) {
    if (ship.mass <= largestSingle + EPSILON) continue
    if (ship.mass > advancedCapacity + EPSILON) {
      problems.push(
        `${ship.id} at ${ship.mass} mass is larger than any individual tug's capacity, and only Advanced FTL Drives may combine (11.6)`,
      )
    }
  }
  return { legal: problems.length === 0, capacity, load: total, problems }
}

// ---------------------------------------------------------------------------
// 11.7 Battleriders and Motherships
// ---------------------------------------------------------------------------

/**
 * *"The maximum mass for any battlerider is 60, following the science fiction
 * convention that battleriders are smaller than the FTL-capable Motherships"*
 * (11.7).
 */
export const MAX_BATTLERIDER_MASS = 60

export interface BattleriderFit {
  id: string
  mass: number
  /** *"they do not pay mass or points cost for an FTL Drive"* (11.7). */
  ftl: FtlKind
  /** *"A fleet with battleriders must deploy the Motherships as well"* (11.7). */
  mothershipId: string | null
}

/**
 * The half of 11.7 a shipyard can check: mass and drive.
 *
 * Whether the Mothership is actually coming is a fact about the fleet, not
 * about the hull on the drawing board, so it lives in `validateFleetFtl` and
 * is checked when the fleet is assembled. A rider is a legal design on its
 * own; it is an illegal *fleet* without its Mothership.
 */
export function validateBattleriderDesign(fit: Omit<BattleriderFit, 'mothershipId'>): string[] {
  const problems: string[] = []
  if (fit.mass > MAX_BATTLERIDER_MASS + EPSILON) {
    problems.push(`a battlerider is ${MAX_BATTLERIDER_MASS} mass at most (11.7)`)
  }
  if (fit.mass <= 0) problems.push('a battlerider needs a hull (11.7)')
  if (fit.ftl !== 'none') {
    problems.push('battleriders do not pay mass or points cost for an FTL Drive (11.7)')
  }
  return problems
}

/**
 * *"If the Mothership makes an FTL entry, the battleriders cannot detach and
 * move independently until the next turn"* (11.7).
 *
 * `mothershipEntryTurn` is null for a Mothership already on the table at the
 * start of the battle, which has nothing to wait for.
 */
export function canDetachBattlerider(mothershipEntryTurn: number | null, turn: number): boolean {
  if (mothershipEntryTurn === null) return true
  return turn > mothershipEntryTurn
}

/**
 * How an attached battlerider is defended (11.7): *"Until they detach, only the
 * Mothership can be fired at and battleriders are protected by the Mothership's
 * screens (but not armor). Damage received can be applied to either the
 * Mothership or battleriders at the choice of the defending player."*
 *
 * Four asymmetries in one sentence, and the screens/armour split is the one a
 * reader will miss.
 */
export interface AttachedBattleriderDefence {
  /** The only hull that may be fired at while the riders are attached. */
  targetableId: string
  screensApply: boolean
  armourApplies: boolean
  /** Hulls the defending player may put damage on. */
  damageMayBeAllocatedTo: string[]
  note: string
}

export function attachedBattleriderDefence(
  mothershipId: string,
  riderIds: readonly string[],
): AttachedBattleriderDefence {
  return {
    targetableId: mothershipId,
    screensApply: true,
    armourApplies: false,
    damageMayBeAllocatedTo: [mothershipId, ...riderIds],
    note: 'only the Mothership may be fired at; riders share its screens but not its armour, and the defender chooses where the damage lands (11.7)',
  }
}

/**
 * Check a defending player's damage split (11.7).
 *
 * The choice is the player's — this validates it rather than making it: the
 * split must account for every point taken and may only name hulls that are
 * actually in the group.
 */
export function allocateBattleriderDamage(
  damage: number,
  allocation: ReadonlyArray<{ unitId: string; damage: number }>,
  defence: AttachedBattleriderDefence,
): string[] {
  const problems: string[] = []
  const allocated = sum(allocation.map((entry) => entry.damage))
  for (const entry of allocation) {
    if (entry.damage < 0) problems.push(`${entry.unitId} cannot take negative damage`)
    if (!defence.damageMayBeAllocatedTo.includes(entry.unitId)) {
      problems.push(`${entry.unitId} is not the Mothership or one of its attached battleriders (11.7)`)
    }
  }
  if (allocated !== damage) {
    problems.push(`allocation of ${allocated} does not account for the ${damage} points taken (11.7)`)
  }
  return problems
}

/**
 * What a hull can carry, in mass of other hulls (11.6, 11.7).
 *
 * 11.7 offers a Mothership two ways to pay — *"internal bays or an oversized
 * FTL Drive"* — and a hull may have bought both, so both are counted. Ship
 * bays are 1.5 mass for every 1 mass carried; a tug's spare drive mass is 1
 * for every 5 towed, which is why almost every Mothership in a fleet list is
 * a tug.
 */
export function carryingCapacity(design: ShipDesign): number {
  const bayMass = design.systems
    .filter((system) => system.kind === 'tender')
    .reduce((sum, system) => sum + system.mass, 0)
  const drive =
    design.ftl === 'tug'
      ? tugTransferMass(design.mass, tugDriveMass(design.mass, design.ftlTransferMass ?? 0))
      : 0
  return tenderCapacityFor(bayMass) + drive
}

/** A surviving Mothership's lift, however it is provided — bay space or drive field (11.7). */
export interface MothershipFit {
  id: string
  /** Carrying capacity in mass: `tenderCapacityFor` for bays, `tugTransferMass` for a tug field. */
  capacity: number
}

export interface BattleriderRecovery {
  totalCapacity: number
  totalMass: number
  /** Rider id → the Mothership carrying it home. */
  assignments: Array<{ riderId: string; mothershipId: string }>
  /** *"considered destroyed at the end of the battle"* (11.7). */
  destroyed: string[]
}

/**
 * Which battleriders survive the end of a one-off battle (11.7): *"battleriders
 * are considered destroyed at the end of the battle if there are no surviving
 * Motherships capable of transporting them."*
 *
 * **[reading]** Riders are packed largest-first into the Mothership with the
 * most room left. 11.7 asks whether a Mothership *"capable of transporting
 * them"* survives but never says how a mixed force of riders is assigned to a
 * mixed force of hulls, and the answer changes which riders die. The
 * alternative — reporting the totals and leaving the assignment to the caller —
 * would refuse to answer the question the rule asks, and this is a scoring rule
 * that has to produce a list of dead ships. The packing is a heuristic, not an
 * optimum; it is exact whenever every rider fits every hull or the capacities
 * are not close, which is every case a fleet list produces.
 */
export function battleriderRecovery(
  riders: readonly BattleriderFit[],
  motherships: readonly MothershipFit[],
): BattleriderRecovery {
  const remaining = motherships.map((ship) => ({ id: ship.id, left: Math.max(0, ship.capacity) }))
  const heaviestFirst = [...riders].sort((a, b) => b.mass - a.mass || a.id.localeCompare(b.id))
  const assignments: BattleriderRecovery['assignments'] = []
  const destroyed: string[] = []

  for (const rider of heaviestFirst) {
    let best: { id: string; left: number } | null = null
    for (const hull of remaining) {
      if (hull.left + EPSILON < rider.mass) continue
      if (best === null || hull.left > best.left) best = hull
    }
    if (best === null) {
      destroyed.push(rider.id)
      continue
    }
    best.left -= rider.mass
    assignments.push({ riderId: rider.id, mothershipId: best.id })
  }

  return {
    totalCapacity: sum(motherships.map((ship) => Math.max(0, ship.capacity))),
    totalMass: sum(riders.map((rider) => Math.max(0, rider.mass))),
    assignments,
    destroyed,
  }
}

// ---------------------------------------------------------------------------
// 11.8 System Defense Ships
// ---------------------------------------------------------------------------

export interface FleetFtlEntry {
  id: string
  ftl: FtlKind
  battlerider?: boolean
  mothershipId?: string | null
}

/**
 * Check a fleet list against 11.8: *"Non-FTL ships – other than battleriders
 * with a Mothership – cannot be part of fleets for one-off battles unless
 * specifically permitted by player agreement or scenario design."*
 *
 * One rule with two exemptions, and a battlerider whose Mothership is not in
 * the list fails both — which is 11.7's *"A fleet with battleriders must deploy
 * the Motherships as well"* arriving from the other direction.
 */
export function validateFleetFtl(
  fleet: readonly FleetFtlEntry[],
  opts: { allowNonFtl?: boolean } = {},
): string[] {
  const problems: string[] = []
  const ftlCapable = new Set(fleet.filter((ship) => ship.ftl !== 'none').map((ship) => ship.id))

  for (const ship of fleet) {
    if (ship.battlerider === true && ship.ftl !== 'none') {
      problems.push(`${ship.id}: battleriders do not carry an FTL Drive (11.7)`)
    }
    if (ship.ftl !== 'none') continue
    if (opts.allowNonFtl === true) continue
    if (ship.battlerider === true) {
      if (ship.mothershipId != null && ftlCapable.has(ship.mothershipId)) continue
      problems.push(`${ship.id}: a battlerider needs an FTL-capable Mothership in the fleet (11.7, 11.8)`)
      continue
    }
    problems.push(
      `${ship.id}: non-FTL ships cannot be part of a fleet for a one-off battle unless the scenario permits it (11.8)`,
    )
  }
  return problems
}

// ---------------------------------------------------------------------------
// 11.9 Jump Gates and Portals
// ---------------------------------------------------------------------------

/** *"10 transfer mass points for every 1 point of FTL Drive mass"* (11.9, Jump Gate). */
export const JUMP_GATE_TRANSFER_MASS_PER_DRIVE_MASS = 10

/** *"hull boxes equal to at least 10% of the transfer mass"* (11.9). */
export const GATE_HULL_FRACTION = 0.1

/** *"the FTL Drive with mass equal to the transfer mass of the Portal"* (11.9). */
export const PORTAL_DRIVE_MASS_PER_TRANSFER_MASS = 1

/**
 * *"Where the game rules are identical for both types the term gate will be
 * used to mean 'Jump Gates and Portals'"* (11.9). They differ in the drive they
 * need and in whether both ends can be on the table; everything else is shared.
 */
export type GateKind = 'jump-gate' | 'portal'

export interface GateDef {
  id: string
  kind: GateKind
  /** *"the gate itself cannot be destroyed by normal weapons fire"* (11.9). */
  natural: boolean
  position: Point
  /**
   * *"more commonly they have one entry and exit facing"* — null for a gate
   * that *"can be used from any angle"* (11.9).
   */
  facing: Course | null
  /** *"the maximum capacity or mass that it is capable of handling in one turn"* (11.9). */
  transferMass: number
  hullBoxes: number
  /** *"If the gate is under control of the player … activation is automatic"* (11.9). */
  playerControlled: boolean
  label?: string
}

export interface GateState {
  hullMarked: number
  /** *"the gate FTL failed a threshold check"* (11.9, 4.11) — set by `threshold.ts`. */
  ftlFailed: boolean
  /** The turn from which transfers may be made, or null while inactive. */
  activeFromTurn: number | null
}

/**
 * The FTL drive an artificial gate needs (11.9). A Portal costs ten times the
 * drive of a Jump Gate of the same throughput, *"representing the (usually)
 * higher cost and more advanced technology"* — which is the whole balance of
 * the section.
 */
export function gateDriveMass(kind: GateKind, transferMass: number): number {
  const mass = Math.max(0, transferMass)
  return kind === 'portal'
    ? mass * PORTAL_DRIVE_MASS_PER_TRANSFER_MASS
    : mass / JUMP_GATE_TRANSFER_MASS_PER_DRIVE_MASS
}

/**
 * *"A Jump Gate should also have hull boxes equal to at least 10% of the
 * transfer mass"* (11.9). Rounded up because it is a stated *minimum* and hull
 * boxes are counted, not measured.
 */
export function gateMinimumHullBoxes(transferMass: number): number {
  return Math.ceil(Math.max(0, transferMass) * GATE_HULL_FRACTION)
}

/**
 * Check a gate's build against 11.9. Natural gates are exempt from all of it:
 * *"The capacity of natural gates is usually very high to unlimited, and the
 * gate itself cannot be destroyed by normal weapons fire, so no record keeping
 * is necessary."*
 */
export function validateGateBuild(gate: GateDef, driveMass: number): string[] {
  if (gate.natural) return []
  const problems: string[] = []
  if (gate.transferMass <= 0) problems.push('an artificial gate needs a transfer mass (11.9)')
  const needed = gateDriveMass(gate.kind, gate.transferMass)
  if (driveMass + EPSILON < needed) {
    problems.push(
      `${gate.kind === 'portal' ? 'a Portal' : 'a Jump Gate'} of transfer mass ${gate.transferMass} needs ${needed} mass of FTL Drive (11.9)`,
    )
  }
  const minimumHull = gateMinimumHullBoxes(gate.transferMass)
  if (gate.hullBoxes < minimumHull) {
    problems.push(`a gate of transfer mass ${gate.transferMass} needs at least ${minimumHull} hull boxes (11.9)`)
  }
  return problems
}

/**
 * The gate's capacity as damaged (11.9): *"For each 10% of hull boxes marked
 * off the current transfer mass is reduced in proportion: a Jump Gate that
 * begins with a transfer mass of 60 and 6 hull boxes will be reduced to 50 at 5
 * hull boxes, 40 at 4, and so on."*
 *
 * **[reading]** Rounds down. The book's example divides evenly and settles
 * nothing; a transfer mass is the load the gate *"is capable of handling"*, so
 * a fractional remainder is capacity the gate does not have. Rounding to
 * nearest would let a gate at 7/8 hull lift a hull it cannot quite reach.
 *
 * A natural gate's capacity is *"very high to unlimited"*, and it cannot be
 * damaged by weapons fire, so it is reported as unlimited.
 */
export function currentTransferMass(gate: GateDef, state: GateState): number {
  if (gate.natural) return Number.POSITIVE_INFINITY
  if (gate.hullBoxes <= 0) return 0
  const remaining = Math.max(0, gate.hullBoxes - Math.max(0, state.hullMarked))
  return Math.floor((gate.transferMass * remaining) / gate.hullBoxes)
}

export interface GateActivationResult {
  rolled: boolean
  roll: number | null
  /** *"On a roll of 1, 2, or 3 the activation is delayed that many turns"* (11.9). */
  delayTurns: number
  /** The turn from which the gate may be used for transfers. */
  activeFromTurn: number
  note: string
}

/**
 * Activate a gate (11.9).
 *
 * > "The player writes a 'Gate Activate' order at the beginning of the turn and
 * > announces the activation when ships are moved. The gate may be used for
 * > transfers on the following turn until deactivated again. If the gate is
 * > under control of the player … activation is automatic. If the gate is not
 * > under control and an attacker wishes to activate it … the defender rolls a
 * > D6 … On a roll of 1, 2, or 3 the activation is delayed that many turns. On
 * > a roll of 4, 5, or 6 the activation succeeds immediately."
 *
 * Note whose dice these are: the *defender* rolls, even though it is the
 * attacker who wants the gate.
 *
 * **[reading]** "Succeeds immediately" still means usable from the following
 * turn. The paragraph opens with the general rule — the gate *"may be used for
 * transfers on the following turn"* — and the D6 only decides whether the
 * activation itself is delayed; "immediately" is set against "delayed that many
 * turns", not against "the following turn". A controlled gate, whose activation
 * is "automatic", plainly still waits a turn, and the alternative would make a
 * captured enemy gate faster to switch on than one's own.
 *
 * A natural jump point needs no activation at all: *"obviously a ship would not
 * need to activate it"* (11.10).
 */
export function gateActivation(gate: GateDef, orderTurn: number, rng: Rng): GateActivationResult {
  if (gate.natural) {
    return {
      rolled: false,
      roll: null,
      delayTurns: 0,
      activeFromTurn: orderTurn,
      note: 'a natural jump point needs no activation (11.10)',
    }
  }
  if (gate.playerControlled) {
    return {
      rolled: false,
      roll: null,
      delayTurns: 0,
      activeFromTurn: orderTurn + 1,
      note: 'the gate is under the player’s control, so activation is automatic (11.9)',
    }
  }
  const roll = d6(rng)
  const delayTurns = roll <= 3 ? roll : 0
  return {
    rolled: true,
    roll,
    delayTurns,
    activeFromTurn: orderTurn + 1 + delayTurns,
    note:
      delayTurns > 0
        ? `activation delayed ${delayTurns} turn(s) (11.9)`
        : 'activation succeeds immediately (11.9)',
  }
}

/** Whether the gate may be used for transfers this turn (11.9). */
export function isGateActive(gate: GateDef, state: GateState, turn: number): boolean {
  if (gate.natural) return true
  return state.activeFromTurn !== null && turn >= state.activeFromTurn
}

/**
 * Whether a ship at `from` is on the gate's working side (11.9): *"Some gates
 * can be used from any angle, but more commonly they have one entry and exit
 * facing."*
 *
 * **[reading]** The single facing is read as 4.2's 60° forward arc. The book
 * says "facing", and an arc is the engine's only representation of a direction
 * a thing can be approached from. An exact course match — the other reading —
 * would mean a gate usable only by a ship on precisely one of twelve headings,
 * which no tabletop measurement could enforce and which *"the marker or model
 * should be clearly marked"* does not suggest.
 */
export function gateBearsOn(gate: GateDef, from: Point): boolean {
  if (gate.facing === null) return true
  // A ship standing on the gate is not on either side of it — it is at it,
  // which is where 11.9 puts a ship about to transfer. `arcTo` of a zero-length
  // vector has no answer, so the question is refused rather than guessed.
  if (distance(gate.position, from) <= EPSILON) return true
  return arcTo(gate.position, gate.facing, from) === 'F'
}

/** Opposite point on the twelve-point clock face (3.1) — a gate facing 9 emits on 3. */
function oppositeCourse(course: Course): Course {
  return ((((course + 6 - 1) % 12) + 1) as Course)
}

export type GateTransferOutcome = 'transferred' | 'backed-out' | 'destroyed'

export interface GateTransferShip {
  id: string
  mass: number
}

export interface GateTransferResult {
  refused: string
  /** True when capacity covered the load and the gate's FTL was sound. */
  clean: boolean
  capacity: number
  load: number
  rolled: boolean
  ships: Array<{
    id: string
    roll: number | null
    outcome: GateTransferOutcome
    /** Where a ship that backed out ends up, and at what velocity (11.9). */
    position: Point | null
    velocity: number | null
  }>
  note: string
}

/**
 * Send ships out through a gate (11.9).
 *
 * > "At the end of the turn, the transfer takes place. If the transfer mass of
 * > the gate exceeds that of the combined ships entering, they all transfer
 * > successfully. If the transfer mass was reduced due to damage or the gate
 * > FTL failed a threshold check, roll 1D6 die for each ship. On a roll of 1
 * > the ship transferred successfully, on a roll of 2 it manages to back out in
 * > time and remains at the location of the gate with a velocity of zero, on a
 * > roll of 3 or higher it is destroyed."
 *
 * This is the most inverted table in section 11 and the one worth reading
 * twice: **1 is the good result** and two thirds of the die kills the ship. A
 * reader who carries 11.4's "1 means nothing happened" across to here will lose
 * a fleet.
 *
 * **[reading]** *"exceeds"* is read as "is at least". Taken literally a gate of
 * transfer mass 60 could not cleanly move exactly 60 mass, but the same section
 * defines transfer mass as *"the maximum capacity or mass that it is capable of
 * handling in one turn"*, and a maximum is inclusive; strict `>` would make a
 * gate's printed rating a mass it cannot handle.
 *
 * **[reading]** An overloaded but undamaged gate uses the same per-ship roll.
 * The text gives the clean transfer when capacity covers the load and the roll
 * when the gate is damaged or its FTL has failed — the two ways capacity comes
 * up short in play — and says nothing about an undamaged gate simply asked for
 * too much. The roll is stated as the consequence of insufficient capacity, so
 * that is what insufficient capacity gets. The alternative, refusing the order,
 * would invent a refusal the book never states, and 11.2 shows the book saying
 * "only permitted" when it means a thing is forbidden.
 */
export function resolveGateTransfer(
  gate: GateDef,
  state: GateState,
  ships: readonly GateTransferShip[],
  turn: number,
  rng: Rng,
): GateTransferResult {
  const capacity = currentTransferMass(gate, state)
  const load = sum(ships.map((ship) => Math.max(0, ship.mass)))

  if (!isGateActive(gate, state, turn)) {
    return {
      refused: 'artificial gates must be activated before use (11.9)',
      clean: false,
      capacity,
      load,
      rolled: false,
      ships: [],
      note: '',
    }
  }

  const clean = !state.ftlFailed && capacity + EPSILON >= load
  if (clean) {
    return {
      refused: '',
      clean: true,
      capacity,
      load,
      rolled: false,
      ships: ships.map((ship) => ({
        id: ship.id,
        roll: null,
        outcome: 'transferred' as const,
        position: null,
        velocity: null,
      })),
      note: 'the gate’s transfer mass covers the combined ships, so they all transfer successfully (11.9)',
    }
  }

  return {
    refused: '',
    clean: false,
    capacity,
    load,
    rolled: true,
    ships: ships.map((ship) => {
      const roll = d6(rng)
      if (roll === 1) {
        return { id: ship.id, roll, outcome: 'transferred' as const, position: null, velocity: null }
      }
      if (roll === 2) {
        // "remains at the location of the gate with a velocity of zero".
        return {
          id: ship.id,
          roll,
          outcome: 'backed-out' as const,
          position: { ...gate.position },
          velocity: 0,
        }
      }
      return { id: ship.id, roll, outcome: 'destroyed' as const, position: null, velocity: null }
    }),
    note: state.ftlFailed
      ? 'the gate’s FTL has failed a threshold check, so each ship rolls (11.9)'
      : `the gate can handle ${capacity} mass against a load of ${load}, so each ship rolls (11.9)`,
  }
}

export interface GateEntryOrder {
  /** *"a velocity up to the maximum rating of its main drive"* (11.9, 3.2). */
  velocity: number
  driveRating: number
  /** Required only for a gate usable from any angle, which has no facing to reverse. */
  course?: Course
}

export interface GateEntryResult {
  placed: boolean
  reason: string
  origin: Point
  position: Point
  course: Course | null
  velocity: number
}

/**
 * Bring a ship onto the table through a gate (11.9).
 *
 * > "To enter through a gate, a ship likewise writes a 'Gate Entry' movement
 * > order with a velocity up to the maximum rating of its main drive. In the
 * > Ship Movement Phase the entering ship is placed on the gate with an initial
 * > course that is 180° opposite (3 in the example above) and then moves the
 * > distance specified by the velocity order."
 *
 * A gate facing 9 therefore emits ships on course 3, which is the book's own
 * parenthesis. Gates never scatter — *"Ships that enter or exit normal space
 * through a Jump Gate or Portal never suffer from direction or distance errors,
 * unlike normal FTL Drives"* — and, **[reading]**, they take no proximity
 * danger roll either: 11.9 puts gates *"near planets or space stations"* as
 * routine civilian infrastructure and sells them on *"a more accurate arrival
 * point"*, so a gate that fired 11.5's roll at its own station on every arrival
 * would be unusable in the setting that describes it. The alternative is the
 * literal reading of the silence, which applies 11.5's roll around the gate;
 * a caller who wants it can still call `resolveFtlEntryDanger`.
 */
export function gateEntry(gate: GateDef, order: GateEntryOrder): GateEntryResult {
  const origin = { ...gate.position }
  const refuse = (reason: string): GateEntryResult => ({
    placed: false,
    reason,
    origin,
    position: origin,
    course: null,
    velocity: 0,
  })

  const course = gate.facing !== null ? oppositeCourse(gate.facing) : order.course
  if (course === undefined) {
    return refuse('a gate usable from any angle needs an entry course to be nominated (11.9)')
  }
  if (order.velocity < 0) return refuse('velocity cannot be negative (3.2)')
  if (order.velocity > order.driveRating + EPSILON) {
    return refuse(
      `gate entry velocity of ${order.velocity} exceeds the ship's main drive rating of ${order.driveRating} (11.9)`,
    )
  }

  return {
    placed: true,
    reason: '',
    origin,
    position: moveShip(origin, course, order.velocity, 0).position,
    course,
    velocity: order.velocity,
  }
}

/**
 * A Portal with both ends on the table (11.9): *"If for some reason both ends
 * of the Portal are on the playing area, a ship exiting through one and
 * entering again through the other does so with the same velocity that it
 * entered."*
 *
 * Velocity is carried across untouched — it is not re-ordered, so the drive
 * rating does not cap it — and the course comes from the receiving end's facing
 * like any other gate entry. A pair of *Jump Gates* is refused: 11.9's defining
 * difference is that *"The two Jump Gates are not linked"*.
 */
export function portalPairTransit(
  entry: GateDef,
  exit: GateDef,
  velocity: number,
  course?: Course,
): GateEntryResult {
  if (entry.kind !== 'portal' || exit.kind !== 'portal') {
    return {
      placed: false,
      reason: 'the two Jump Gates are not linked; only a Portal is a fixed connection (11.9)',
      origin: { ...exit.position },
      position: { ...exit.position },
      course: null,
      velocity: 0,
    }
  }
  return gateEntry(exit, { velocity, driveRating: velocity, course })
}

// ---------------------------------------------------------------------------
// 11.10 Natural Jump Gates or Jump Points (optional)
// ---------------------------------------------------------------------------

/**
 * The disorientation a jump point inflicts (11.10). Field names match
 * `game.ts`'s `OngoingEffect` so the integrator can push it onto `ship.ongoing`
 * unchanged, which is also what makes `threshold.ts`'s `isOutOfControl` see it.
 */
export interface JumpPointDisorientation {
  source: 'jump-point'
  appliedTurn: number
  expiresAfterTurn: number
  outOfControl: boolean
  note: string
}

/**
 * *"It is recommended that ships be 'disorientated' upon exiting a jump point.
 * Ships exiting a jump point function as if they have taken a bridge critical
 * hit until the next turn when they make function normally."* (11.10)
 *
 * **[reading]** One turn out of control, with no 10.3 die rolled. 11.10 borrows
 * the bridge hit's *effect* and then fixes its own duration — "until the next
 * turn" — while 10.3's die can give five turns or permanence, which that
 * sentence explicitly denies. The alternative, rolling the die and capping the
 * result at one turn, produces the same effect through a roll that can never
 * matter and would consume an RNG draw the replay journal then has to carry.
 */
export function jumpPointDisorientation(exitTurn: number): JumpPointDisorientation {
  return {
    source: 'jump-point',
    appliedTurn: exitTurn,
    expiresAfterTurn: exitTurn,
    outOfControl: true,
    note: 'disorientated on exiting a jump point: out of control as if from a bridge critical hit until the next turn (11.10, 10.3)',
  }
}

/** Whether the disorientation still binds on `turn` (11.10). */
export function isDisoriented(effect: JumpPointDisorientation, turn: number): boolean {
  return turn <= effect.expiresAfterTurn
}
