/* GENERATED by tools/build_ssd_icons.py from docs/ssd-icon-sheet.svg.
 * Do not hand-edit: edit the sheet and re-run the tool. */

export interface SsdIcon {
  /** Symbol id in the sprite, without the `ssd-` prefix. */
  id: string
  /** The sheet's own printed label. */
  label: string
  section: string
  /** Width over height of the symbol as drawn. */
  aspect: number
  /** The symbol's own coordinate system, for drawing on top of it. */
  viewBox: string
  /**
   * Where the sheet printed a sample number, for the seven symbols whose
   * number is the ship's rather than the symbol's. The sample itself is
   * marked `ssd-sample` and hidden; draw the real value here instead.
   */
  numberSlot?: { x: number; y: number; size: number; means: string }
}

export const SSD_ICONS: readonly SsdIcon[] = [
 {
  "id": "armour",
  "label": "Armour",
  "section": "Hull and armour",
  "aspect": 1.0,
  "viewBox": "202.0 2.0 556.0 556.0"
 },
 {
  "id": "armour-damaged",
  "label": "Armour (damaged)",
  "section": "Hull and armour",
  "aspect": 1.0,
  "viewBox": "202.0 2.0 556.0 556.0"
 },
 {
  "id": "armour-regenerative-damaged",
  "label": "Armour (regenerative, damaged)",
  "section": "Hull and armour",
  "aspect": 1.0,
  "viewBox": "125.5 -75.5 709.0 709.0"
 },
 {
  "id": "armour-regenerative-lost",
  "label": "Armour (regenerative, lost)",
  "section": "Hull and armour",
  "aspect": 1.0,
  "viewBox": "125.5 -75.5 709.0 709.0"
 },
 {
  "id": "armour-regenerative",
  "label": "Armour (regenerative)",
  "section": "Hull and armour",
  "aspect": 1.0,
  "viewBox": "125.5 -75.5 709.0 709.0"
 },
 {
  "id": "hull-box",
  "label": "Hull box",
  "section": "Hull and armour",
  "aspect": 1.0,
  "viewBox": "184.0 -16.0 592.0 592.0"
 },
 {
  "id": "hull-box-crew-star",
  "label": "Hull box (crew star)",
  "section": "Hull and armour",
  "aspect": 1.0,
  "viewBox": "184.0 -16.0 592.0 592.0"
 },
 {
  "id": "hull-box-damaged",
  "label": "Hull box (damaged)",
  "section": "Hull and armour",
  "aspect": 1.0,
  "viewBox": "184.0 -16.0 592.0 592.0"
 },
 {
  "id": "faster-than-light-drive",
  "label": "Faster-Than-Light Drive",
  "section": "Propulsion",
  "aspect": 1.0,
  "viewBox": "18.5 -180.5 922.0 922.0"
 },
 {
  "id": "faster-than-light-drive-advanced",
  "label": "Faster-Than-Light Drive — Advanced",
  "section": "Propulsion",
  "aspect": 1.0,
  "viewBox": "-51.5 -247.5 1058.0 1058.0"
 },
 {
  "id": "main-drive",
  "label": "Main Drive",
  "section": "Propulsion",
  "aspect": 1.0,
  "viewBox": "164.0 -35.5 629.0 629.0",
  "numberSlot": {
   "x": 479.5,
   "y": 343.52,
   "size": 400.0,
   "means": "thrust rating"
  }
 },
 {
  "id": "main-drive-advanced",
  "label": "Main Drive — Advanced",
  "section": "Propulsion",
  "aspect": 1.0,
  "viewBox": "245.0 45.0 470.0 470.0",
  "numberSlot": {
   "x": 480.0,
   "y": 320.0,
   "size": 400.0,
   "means": "thrust rating"
  }
 },
 {
  "id": "advanced-area-defense-fire-control",
  "label": "Advanced Area Defense Fire Control",
  "section": "Systems",
  "aspect": 0.5,
  "viewBox": "349.0 19.0 261.0 522.0"
 },
 {
  "id": "advanced-area-defensive-screen-level-1",
  "label": "Advanced Area Defensive Screen — Level 1",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "280.0 80.0 400.0 400.0"
 },
 {
  "id": "advanced-area-defensive-screen-level-2",
  "label": "Advanced Area Defensive Screen — Level 2",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "280.0 80.0 400.0 400.0"
 },
 {
  "id": "advanced-area-defensive-screen-unleveled",
  "label": "Advanced Area Defensive Screen (unleveled)",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "280.0 80.0 400.0 400.0"
 },
 {
  "id": "advanced-defensive-screen-level-1",
  "label": "Advanced Defensive Screen — Level 1",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "250.0 45.0 460.0 460.0"
 },
 {
  "id": "advanced-defensive-screen-level-2",
  "label": "Advanced Defensive Screen — Level 2",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "250.0 45.0 460.0 460.0"
 },
 {
  "id": "advanced-defensive-screen-unleveled",
  "label": "Advanced Defensive Screen (unleveled)",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "250.0 45.0 460.0 460.0"
 },
 {
  "id": "advanced-fire-control",
  "label": "Advanced Fire Control",
  "section": "Systems",
  "aspect": 0.6667,
  "viewBox": "271.0 -31.25 415.0 622.5"
 },
 {
  "id": "advanced-sensors",
  "label": "Advanced Sensors",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "240.0 34.0 480.0 480.0"
 },
 {
  "id": "antimatter-suicide-charge",
  "label": "Antimatter Suicide Charge",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "195.0 -5.0 569.0 569.0"
 },
 {
  "id": "area-defense-fire-control",
  "label": "Area Defense Fire Control",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "248.0 48.0 464.0 464.0"
 },
 {
  "id": "area-defensive-screen-level-1",
  "label": "Area Defensive Screen — Level 1",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "302.5 102.5 355.0 355.0"
 },
 {
  "id": "area-defensive-screen-level-2",
  "label": "Area Defensive Screen — Level 2",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "302.5 102.5 355.0 355.0"
 },
 {
  "id": "area-defensive-screen-unleveled",
  "label": "Area Defensive Screen (unleveled)",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "302.5 102.5 355.0 355.0"
 },
 {
  "id": "area-ecm-device",
  "label": "Area ECM Device",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "206.0 6.5 547.0 547.0"
 },
 {
  "id": "boarding-torpedo-magazine",
  "label": "Boarding Torpedo Magazine",
  "section": "Systems",
  "aspect": 1.4545,
  "viewBox": "-1.0 -1.0 32.0 22.0"
 },
 {
  "id": "boat-bay",
  "label": "Boat Bay",
  "section": "Systems",
  "aspect": 0.6667,
  "viewBox": "321.33 40.0 315.33 473.0",
  "numberSlot": {
   "x": 479.5,
   "y": 318.5,
   "size": 100.0,
   "means": "craft carried"
  }
 },
 {
  "id": "capital-decoy",
  "label": "Capital Decoy",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "190.0 -9.0 580.0 580.0"
 },
 {
  "id": "cargo-hold",
  "label": "Cargo Hold",
  "section": "Systems",
  "aspect": 0.6667,
  "viewBox": "305.0 17.0 350.0 525.0",
  "numberSlot": {
   "x": 480.0,
   "y": 410.75,
   "size": 131.25,
   "means": "mass carried"
  }
 },
 {
  "id": "cloaking-device",
  "label": "Cloaking Device",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "267.0 67.0 425.0 425.0"
 },
 {
  "id": "cloaking-field",
  "label": "Cloaking Field",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "245.0 45.0 470.0 470.0"
 },
 {
  "id": "cruiser-decoy",
  "label": "Cruiser Decoy",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "190.0 -9.0 580.0 580.0"
 },
 {
  "id": "defensive-screen-level-1",
  "label": "Defensive Screen — Level 1",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "250.0 40.0 460.0 460.0"
 },
 {
  "id": "defensive-screen-level-2",
  "label": "Defensive Screen — Level 2",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "250.0 40.0 460.0 460.0"
 },
 {
  "id": "defensive-screen-unleveled",
  "label": "Defensive Screen (unleveled)",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "250.0 40.0 460.0 460.0"
 },
 {
  "id": "ecm-device",
  "label": "ECM Device",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "212.0 12.5 535.0 535.0"
 },
 {
  "id": "extra-damage-control",
  "label": "Extra Damage Control",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "230.0 30.0 500.0 500.0"
 },
 {
  "id": "extra-marines",
  "label": "Extra Marines",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "310.0 110.0 340.0 340.0"
 },
 {
  "id": "fire-control",
  "label": "Fire Control",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "274.0 75.0 411.0 411.0"
 },
 {
  "id": "gunboat-rack",
  "label": "Gunboat Rack",
  "section": "Systems",
  "aspect": 0.6667,
  "viewBox": "305.0 17.0 350.0 525.0"
 },
 {
  "id": "holofield-generator",
  "label": "Holofield Generator",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "280.0 71.0 400.0 400.0"
 },
 {
  "id": "mine-layer",
  "label": "Mine Layer",
  "section": "Systems",
  "aspect": 0.6667,
  "viewBox": "-19.0 -12.0 358.0 537.0"
 },
 {
  "id": "mine-sweeper",
  "label": "Mine Sweeper",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "255.0 55.0 450.0 450.0"
 },
 {
  "id": "ortillery-system",
  "label": "Ortillery System",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "347.5 200.0 265.0 265.0"
 },
 {
  "id": "passenger-berth",
  "label": "Passenger Berth",
  "section": "Systems",
  "aspect": 0.6667,
  "viewBox": "305.0 17.0 350.0 525.0",
  "numberSlot": {
   "x": 480.0,
   "y": 410.75,
   "size": 131.25,
   "means": "passengers carried"
  }
 },
 {
  "id": "reflex-field-deprecated",
  "label": "Reflex Field (deprecated)",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "265.0 65.0 430.0 430.0"
 },
 {
  "id": "salvo-missile-magazine",
  "label": "Salvo Missile Magazine",
  "section": "Systems",
  "aspect": 1.4545,
  "viewBox": "-1.0 -1.0 32.0 22.0"
 },
 {
  "id": "salvo-missile-magazine-long-range",
  "label": "Salvo Missile Magazine — Long Range",
  "section": "Systems",
  "aspect": 1.4545,
  "viewBox": "-1.0 -1.0 32.0 22.0"
 },
 {
  "id": "salvo-missile-magazine-multistage",
  "label": "Salvo Missile Magazine — Multistage",
  "section": "Systems",
  "aspect": 1.4545,
  "viewBox": "-1.0 -1.0 32.0 22.0"
 },
 {
  "id": "stealth-field-generator",
  "label": "Stealth Field Generator",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "265.0 56.0 430.0 430.0"
 },
 {
  "id": "superior-sensors",
  "label": "Superior Sensors",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "240.0 34.0 480.0 480.0"
 },
 {
  "id": "tender-bay",
  "label": "Tender Bay",
  "section": "Systems",
  "aspect": 0.6667,
  "viewBox": "321.33 40.0 315.33 473.0",
  "numberSlot": {
   "x": 479.5,
   "y": 318.5,
   "size": 100.0,
   "means": "craft carried"
  }
 },
 {
  "id": "troop-berth",
  "label": "Troop Berth",
  "section": "Systems",
  "aspect": 0.6667,
  "viewBox": "305.0 17.0 350.0 525.0",
  "numberSlot": {
   "x": 480.0,
   "y": 410.75,
   "size": 131.25,
   "means": "troops carried"
  }
 },
 {
  "id": "vapour-shroud",
  "label": "Vapour Shroud",
  "section": "Systems",
  "aspect": 1.0,
  "viewBox": "230.0 30.0 500.0 500.0"
 },
 {
  "id": "antimatter-missile",
  "label": "Antimatter Missile",
  "section": "Ordnance",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "boarding-torpedo",
  "label": "Boarding torpedo",
  "section": "Ordnance",
  "aspect": 0.7143,
  "viewBox": "0.0 0.0 10.0 14.0"
 },
 {
  "id": "heavy-missile",
  "label": "Heavy Missile",
  "section": "Ordnance",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "heavy-missile-long-range",
  "label": "Heavy Missile — Long Range",
  "section": "Ordnance",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "heavy-missile-multistage",
  "label": "Heavy Missile — Multistage",
  "section": "Ordnance",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "mine",
  "label": "Mine",
  "section": "Ordnance",
  "aspect": 1.0,
  "viewBox": "440.5 244.0 79.0 79.0"
 },
 {
  "id": "rocket-pod",
  "label": "Rocket Pod",
  "section": "Ordnance",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "salvo-missile",
  "label": "Salvo missile",
  "section": "Ordnance",
  "aspect": 1.0,
  "viewBox": "430.5 148.0 99.0 99.0"
 },
 {
  "id": "salvo-missile-launcher",
  "label": "Salvo Missile Launcher",
  "section": "Ordnance",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "salvo-missile-rack-single-use",
  "label": "Salvo Missile Rack (single-use)",
  "section": "Ordnance",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "salvo-missile-rack-single-use-long-range",
  "label": "Salvo Missile Rack (single-use)- Long Range",
  "section": "Ordnance",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "salvo-missile-rack-single-use-multistage",
  "label": "Salvo Missile Rack (single-use)- Multistage",
  "section": "Ordnance",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "area-defense-system",
  "label": "Area Defense System",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "boarding-torpedo-launcher",
  "label": "Boarding Torpedo Launcher",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-1-beam",
  "label": "Class 1 Beam",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-1-emp-projector",
  "label": "Class 1 EMP Projector",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-1-graser",
  "label": "Class 1Graser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-1-gravitic-gun",
  "label": "Class 1Gravitic Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-1-heavy-graser",
  "label": "Class 1Heavy Graser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-1-heavy-high-intensity-graser",
  "label": "Class 1Heavy High-Intensity Graser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-1-high-intensity-graser",
  "label": "Class 1High-Intensity Graser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-1-k-gun",
  "label": "Class 1K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-1-long-range-k-gun",
  "label": "Class 1Long-Range K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-1-needle-beam",
  "label": "Class 1Needle Beam",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-1-phaser",
  "label": "Class 1Phaser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-1-plasma-bolt-launcher",
  "label": "Class 1Plasma Bolt Launcher",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-1-plasma-cannon",
  "label": "Class 1Plasma Cannon",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-1-short-range-k-gun",
  "label": "Class 1Short-Range K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-26.0 24.0 652.0 652.0"
 },
 {
  "id": "class-1-transporter-beam",
  "label": "Class 1Transporter Beam",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-2-beam",
  "label": "Class 2 Beam",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-2-emp-projector",
  "label": "Class 2 EMP Projector",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-2-graser",
  "label": "Class 2Graser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-2-gravitic-gun",
  "label": "Class 2Gravitic Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-2-heavy-graser",
  "label": "Class 2Heavy Graser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-2-heavy-high-intensity-graser",
  "label": "Class 2Heavy High-Intensity Graser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-2-high-intensity-graser",
  "label": "Class 2High-Intensity Graser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-2-k-gun",
  "label": "Class 2K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-2-long-range-k-gun",
  "label": "Class 2Long-Range K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-2-needle-beam",
  "label": "Class 2Needle Beam",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-2-phaser",
  "label": "Class 2Phaser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-2-plasma-bolt-launcher",
  "label": "Class 2Plasma Bolt Launcher",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-2-plasma-cannon",
  "label": "Class 2Plasma Cannon",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-2-short-range-k-gun",
  "label": "Class 2Short-Range K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-26.0 24.0 652.0 652.0"
 },
 {
  "id": "class-2-transporter-beam",
  "label": "Class 2Transporter Beam",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-3-beam",
  "label": "Class 3 Beam",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-3-emp-projector",
  "label": "Class 3 EMP Projector",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-3-graser",
  "label": "Class 3Graser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-3-gravitic-gun",
  "label": "Class 3Gravitic Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-3-heavy-graser",
  "label": "Class 3Heavy Graser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-3-heavy-high-intensity-graser",
  "label": "Class 3Heavy High-Intensity Graser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-3-high-intensity-graser",
  "label": "Class 3High-Intensity Graser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-3-k-gun",
  "label": "Class 3K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-3-long-range-k-gun",
  "label": "Class 3Long-Range K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-3-needle-beam",
  "label": "Class 3Needle Beam",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-3-phaser",
  "label": "Class 3Phaser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-3-plasma-bolt-launcher",
  "label": "Class 3Plasma Bolt Launcher",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-3-plasma-cannon",
  "label": "Class 3Plasma Cannon",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-3-short-range-k-gun",
  "label": "Class 3Short-Range K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-26.0 24.0 652.0 652.0"
 },
 {
  "id": "class-3-transporter-beam",
  "label": "Class 3Transporter Beam",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-4-beam",
  "label": "Class 4 Beam",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-4-emp-projector",
  "label": "Class 4 EMP Projector",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-4-graser",
  "label": "Class 4Graser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-4-high-intensity-graser",
  "label": "Class 4High-Intensity Graser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-4-k-gun",
  "label": "Class 4K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-4-long-range-k-gun",
  "label": "Class 4Long-Range K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-4-needle-beam",
  "label": "Class 4Needle Beam",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-4-phaser",
  "label": "Class 4Phaser",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-4-plasma-bolt-launcher",
  "label": "Class 4Plasma Bolt Launcher",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-4-plasma-cannon",
  "label": "Class 4Plasma Cannon",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-4-short-range-k-gun",
  "label": "Class 4Short-Range K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-26.0 24.0 652.0 652.0"
 },
 {
  "id": "class-4-transporter-beam",
  "label": "Class 4Transporter Beam",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-5-k-gun",
  "label": "Class 5K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-5-long-range-k-gun",
  "label": "Class 5Long-Range K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-5-short-range-k-gun",
  "label": "Class 5Short-Range K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-26.0 24.0 652.0 652.0"
 },
 {
  "id": "class-6-k-gun",
  "label": "Class 6K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-6-long-range-k-gun",
  "label": "Class 6Long-Range K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "class-6-short-range-k-gun",
  "label": "Class 6Short-Range K-Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-26.0 24.0 652.0 652.0"
 },
 {
  "id": "fusion-array",
  "label": "Fusion Array",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "fusion-array-flare",
  "label": "Fusion Array- Flare",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "fusion-array-torpedo",
  "label": "Fusion Array- Torpedo",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "gatling-battery",
  "label": "Gatling Battery",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "grapeshot-launcher",
  "label": "Grapeshot Launcher",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "220.0 20.0 520.0 520.0"
 },
 {
  "id": "long-range-pulse-torpedos",
  "label": "Long-Range Pulse Torpedos",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "meson-projector",
  "label": "Meson Projector",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "multiple-kinetic-penetrator",
  "label": "Multiple Kinetic Penetrator",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "point-defense-system",
  "label": "Point Defense System",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "378.0 178.0 204.0 204.0"
 },
 {
  "id": "pulse-torpedos",
  "label": "Pulse Torpedos",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "pulser-long-range",
  "label": "Pulser — Long Range",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "pulser-medium-range",
  "label": "Pulser — Medium Range",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "pulser-short-range",
  "label": "Pulser — Short Range",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "pulser-undefined-range",
  "label": "Pulser — Undefined Range",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "scatter-gun",
  "label": "Scatter Gun",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "270.0 70.0 420.0 420.0"
 },
 {
  "id": "short-range-pulse-torpedos",
  "label": "Short-Range Pulse Torpedos",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "spinal-mount-beam-long-range",
  "label": "Spinal Mount- Beam — Long Range",
  "section": "Weapons",
  "aspect": 0.6667,
  "viewBox": "290.0 5.0 380.0 570.0"
 },
 {
  "id": "spinal-mount-beam-medium-range",
  "label": "Spinal Mount- Beam — Medium Range",
  "section": "Weapons",
  "aspect": 0.6667,
  "viewBox": "290.0 5.0 380.0 570.0"
 },
 {
  "id": "spinal-mount-beam-short-range",
  "label": "Spinal Mount- Beam — Short Range",
  "section": "Weapons",
  "aspect": 0.6667,
  "viewBox": "290.0 5.0 380.0 570.0"
 },
 {
  "id": "spinal-mount-nova-cannon-deprecated",
  "label": "Spinal Mount- Nova Cannon (deprecated)",
  "section": "Weapons",
  "aspect": 0.6829,
  "viewBox": "340.0 75.0 280.0 410.0"
 },
 {
  "id": "spinal-mount-wave-gun-deprecated",
  "label": "Spinal Mount- Wave Gun (deprecated)",
  "section": "Weapons",
  "aspect": 0.7451,
  "viewBox": "290.0 30.0 380.0 510.0"
 },
 {
  "id": "turreted-submunitions-pack",
  "label": "Turreted Submunitions Pack",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "twin-particle-array",
  "label": "Twin Particle Array",
  "section": "Weapons",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "fighter-rack",
  "label": "Fighter Rack",
  "section": "Fighter bays and wings",
  "aspect": 0.6667,
  "viewBox": "320.0 35.75 319.0 478.5"
 },
 {
  "id": "hangar-bay",
  "label": "Hangar Bay",
  "section": "Fighter bays and wings",
  "aspect": 0.6667,
  "viewBox": "320.0 35.75 319.0 478.5"
 },
 {
  "id": "hangar-bay-assault-shuttles",
  "label": "Hangar Bay —Assault Shuttles",
  "section": "Fighter bays and wings",
  "aspect": 0.6667,
  "viewBox": "320.0 35.75 319.0 478.5"
 },
 {
  "id": "hangar-bay-attack-fighter",
  "label": "Hangar Bay —Attack Fighter",
  "section": "Fighter bays and wings",
  "aspect": 0.6667,
  "viewBox": "320.0 35.75 319.0 478.5"
 },
 {
  "id": "hangar-bay-graser-fighter",
  "label": "Hangar Bay —Graser Fighter",
  "section": "Fighter bays and wings",
  "aspect": 0.6667,
  "viewBox": "320.0 35.75 319.0 478.5"
 },
 {
  "id": "hangar-bay-interceptor",
  "label": "Hangar Bay —Interceptor",
  "section": "Fighter bays and wings",
  "aspect": 0.6667,
  "viewBox": "320.0 35.75 319.0 478.5"
 },
 {
  "id": "hangar-bay-light-attack-fighter",
  "label": "Hangar Bay —Light Attack Fighter",
  "section": "Fighter bays and wings",
  "aspect": 0.6667,
  "viewBox": "320.0 35.75 319.0 478.5"
 },
 {
  "id": "hangar-bay-light-fighter",
  "label": "Hangar Bay —Light Fighter",
  "section": "Fighter bays and wings",
  "aspect": 0.6667,
  "viewBox": "320.0 35.75 319.0 478.5"
 },
 {
  "id": "hangar-bay-light-interceptor",
  "label": "Hangar Bay —Light Interceptor",
  "section": "Fighter bays and wings",
  "aspect": 0.6667,
  "viewBox": "320.0 35.75 319.0 478.5"
 },
 {
  "id": "hangar-bay-missile-fighter",
  "label": "Hangar Bay —Missile Fighter",
  "section": "Fighter bays and wings",
  "aspect": 0.6667,
  "viewBox": "320.0 35.75 319.0 478.5"
 },
 {
  "id": "hangar-bay-mkp-fighter",
  "label": "Hangar Bay —MKP Fighter",
  "section": "Fighter bays and wings",
  "aspect": 0.6667,
  "viewBox": "320.0 35.75 319.0 478.5"
 },
 {
  "id": "hangar-bay-multi-role-fighter",
  "label": "Hangar Bay —Multi-Role Fighter",
  "section": "Fighter bays and wings",
  "aspect": 0.6667,
  "viewBox": "320.0 35.75 319.0 478.5"
 },
 {
  "id": "hangar-bay-plasma-fighter",
  "label": "Hangar Bay —Plasma Fighter",
  "section": "Fighter bays and wings",
  "aspect": 0.6667,
  "viewBox": "320.0 35.75 319.0 478.5"
 },
 {
  "id": "hangar-bay-standard-fighter",
  "label": "Hangar Bay —Standard Fighter",
  "section": "Fighter bays and wings",
  "aspect": 0.6667,
  "viewBox": "320.0 35.75 319.0 478.5"
 },
 {
  "id": "hangar-bay-torpedo-fighter",
  "label": "Hangar Bay —Torpedo Fighter",
  "section": "Fighter bays and wings",
  "aspect": 0.6667,
  "viewBox": "320.0 35.75 319.0 478.5"
 },
 {
  "id": "launch-tube",
  "label": "Launch Tube",
  "section": "Fighter bays and wings",
  "aspect": 1.0,
  "viewBox": "220.0 20.0 520.0 520.0"
 },
 {
  "id": "launch-tubew-catapult",
  "label": "Launch Tubew/ Catapult",
  "section": "Fighter bays and wings",
  "aspect": 1.0,
  "viewBox": "-1.0 -1.0 602.0 602.0"
 },
 {
  "id": "gunboat-rack-occupied-sample",
  "label": "Gunboat Rack (occupied sample)",
  "section": "Gunboats",
  "aspect": 0.6667,
  "viewBox": "305.0 17.0 350.0 525.0"
 },
 {
  "id": "core-systems",
  "label": "Core systems",
  "section": "Auxiliary",
  "aspect": 3.0,
  "viewBox": "66.0 142.0 828.0 276.0"
 },
 {
  "id": "flawed-design",
  "label": "Flawed Design",
  "section": "Auxiliary",
  "aspect": 1.0,
  "viewBox": "8.0 -28.0 82.0 82.0"
 }
]

export const SSD_ICON_IDS: ReadonlySet<string> = new Set(SSD_ICONS.map((i) => i.id))
