/**
 * What a designer may buy (14).
 *
 * GENERATED by tools/build_roster.py from the same section 14 tables the
 * roster is priced from — do not hand-edit. Emitting both from one source is
 * the point: a designer offering a cost the roster does not charge is how a
 * fleet quietly becomes unfair.
 *
 * Only flat-cost entries are here. Hulls, drives, FTL, streamlining and
 * screens are fractions of total ship mass and belong to designPricing.ts,
 * which computes them (13.7 - 13.11).
 */

import type { Arc, SystemKind, WeaponClass, WeaponVariant } from '../engine/types'

export interface CatalogueWeapon {
  weaponClass: WeaponClass
  variant: WeaponVariant
  rating: number
  label: string
  /** Arc counts this mounting is sold in, and what each costs (14.4). */
  mountings: ReadonlyArray<{ arcs: number; mass: number; points: number }>
}

export interface CatalogueSystem {
  kind: SystemKind
  label: string
  mass: number
  points: number
}

/** Every arc, for a mounting sold at six. */
export const ALL_ARCS: readonly Arc[] = ['F', 'FS', 'AS', 'A', 'AP', 'FP']

export const CATALOGUE_WEAPONS: readonly CatalogueWeapon[] = [
  { weaponClass: 'beam', variant: 'standard', rating: 1, label: "Beam-1", mountings: [{ arcs: 6, mass: 1, points: 3 }] },
  { weaponClass: 'beam', variant: 'standard', rating: 2, label: "Beam-2", mountings: [{ arcs: 3, mass: 2, points: 6 }, { arcs: 6, mass: 3, points: 9 }] },
  { weaponClass: 'beam', variant: 'standard', rating: 3, label: "Beam-3", mountings: [{ arcs: 1, mass: 4, points: 12 }, { arcs: 2, mass: 5, points: 15 }, { arcs: 3, mass: 6, points: 18 }, { arcs: 4, mass: 7, points: 21 }, { arcs: 5, mass: 8, points: 24 }, { arcs: 6, mass: 9, points: 27 }] },
  { weaponClass: 'beam', variant: 'standard', rating: 4, label: "Beam-4", mountings: [{ arcs: 1, mass: 8, points: 24 }, { arcs: 2, mass: 10, points: 30 }, { arcs: 3, mass: 12, points: 36 }, { arcs: 4, mass: 14, points: 42 }, { arcs: 5, mass: 16, points: 48 }, { arcs: 6, mass: 18, points: 54 }] },
  { weaponClass: 'beam', variant: 'standard', rating: 5, label: "Beam-5", mountings: [{ arcs: 1, mass: 16, points: 48 }, { arcs: 2, mass: 20, points: 60 }, { arcs: 3, mass: 24, points: 72 }, { arcs: 4, mass: 28, points: 84 }, { arcs: 5, mass: 32, points: 96 }, { arcs: 6, mass: 36, points: 108 }] },
  { weaponClass: 'pulse-torpedo', variant: 'standard', rating: 1, label: "Pulse Torp", mountings: [{ arcs: 1, mass: 4, points: 12 }, { arcs: 2, mass: 5, points: 15 }, { arcs: 3, mass: 6, points: 18 }] },
  { weaponClass: 'pulse-torpedo', variant: 'short', rating: 1, label: "SR Pulse Torp", mountings: [{ arcs: 1, mass: 2, points: 6 }, { arcs: 3, mass: 3, points: 9 }] },
  { weaponClass: 'pulse-torpedo', variant: 'long', rating: 1, label: "LR Pulse Torp", mountings: [{ arcs: 1, mass: 8, points: 24 }, { arcs: 2, mass: 10, points: 30 }, { arcs: 3, mass: 12, points: 36 }] },
  { weaponClass: 'k-gun', variant: 'standard', rating: 1, label: "K-1", mountings: [{ arcs: 6, mass: 2, points: 8 }] },
  { weaponClass: 'k-gun', variant: 'standard', rating: 2, label: "K-2", mountings: [{ arcs: 1, mass: 3, points: 12 }, { arcs: 2, mass: 4, points: 16 }] },
  { weaponClass: 'k-gun', variant: 'standard', rating: 3, label: "K-3", mountings: [{ arcs: 1, mass: 5, points: 20 }] },
  { weaponClass: 'k-gun', variant: 'standard', rating: 4, label: "K-4", mountings: [{ arcs: 1, mass: 8, points: 32 }] },
  { weaponClass: 'heavy-missile', variant: 'standard', rating: 1, label: "Heavy Missile", mountings: [{ arcs: 3, mass: 2, points: 6 }] },
  { weaponClass: 'heavy-missile', variant: 'extended', rating: 1, label: "ER Missile", mountings: [{ arcs: 3, mass: 3, points: 9 }] },
  { weaponClass: 'salvo-missile-rack', variant: 'standard', rating: 1, label: "SM Rack", mountings: [{ arcs: 3, mass: 4, points: 12 }] },
  { weaponClass: 'salvo-missile-launcher', variant: 'standard', rating: 1, label: "SML", mountings: [{ arcs: 3, mass: 3, points: 9 }] },
  { weaponClass: 'submunition-pack', variant: 'standard', rating: 1, label: "Submunition", mountings: [{ arcs: 3, mass: 1, points: 3 }] },
  { weaponClass: 'gatling', variant: 'standard', rating: 1, label: "Gatling", mountings: [{ arcs: 1, mass: 2, points: 8 }, { arcs: 3, mass: 3, points: 12 }, { arcs: 6, mass: 4, points: 16 }] },
  { weaponClass: 'needle-beam', variant: 'standard', rating: 1, label: "Needle-1", mountings: [{ arcs: 2, mass: 2, points: 6 }, { arcs: 3, mass: 3, points: 9 }] },
  { weaponClass: 'plasma-cannon', variant: 'standard', rating: 1, label: "Plasma-1", mountings: [{ arcs: 3, mass: 1, points: 3 }, { arcs: 6, mass: 2, points: 6 }] },
  { weaponClass: 'plasma-cannon', variant: 'standard', rating: 2, label: "Plasma-2", mountings: [{ arcs: 3, mass: 4, points: 12 }, { arcs: 6, mass: 6, points: 18 }] },
  { weaponClass: 'graser', variant: 'standard', rating: 1, label: "Graser-1", mountings: [{ arcs: 3, mass: 1, points: 3 }, { arcs: 6, mass: 2, points: 6 }] },
  { weaponClass: 'graser', variant: 'standard', rating: 2, label: "Graser-2", mountings: [{ arcs: 3, mass: 4, points: 12 }, { arcs: 6, mass: 6, points: 18 }] },
  { weaponClass: 'fusion-array', variant: 'standard', rating: 1, label: "Fusion Array", mountings: [{ arcs: 1, mass: 3, points: 9 }, { arcs: 2, mass: 4, points: 12 }, { arcs: 3, mass: 5, points: 15 }] },
  { weaponClass: 'pulser', variant: 'standard', rating: 1, label: "Pulser", mountings: [{ arcs: 1, mass: 2, points: 10 }, { arcs: 3, mass: 3, points: 15 }, { arcs: 6, mass: 4, points: 20 }] },
]

export const CATALOGUE_SYSTEMS: readonly CatalogueSystem[] = [
  { kind: 'adfc', label: "ADFC", mass: 2, points: 8 },
  { kind: 'ads', label: "ADS", mass: 2, points: 6 },
  { kind: 'ads', label: "ADS", mass: 3, points: 9 },
  { kind: 'advanced-adfc', label: "Adv ADFC", mass: 2, points: 10 },
  { kind: 'advanced-firecon', label: "Adv FireCon", mass: 1, points: 5 },
  { kind: 'antimatter-charge', label: "AM Charge", mass: 1, points: 5 },
  { kind: 'area-ecm', label: "Area ECM", mass: 2, points: 6 },
  { kind: 'boat-bay', label: "Boat Bay", mass: 1.5, points: 0 },
  { kind: 'cargo', label: "Cargo", mass: 1, points: 0 },
  { kind: 'ecm', label: "ECM", mass: 1, points: 3 },
  { kind: 'enhanced-sensors', label: "Enh Sensors", mass: 2, points: 8 },
  { kind: 'firecon', label: "FireCon", mass: 1, points: 4 },
  { kind: 'grapeshot', label: "Grapeshot", mass: 1, points: 4 },
  { kind: 'hangar-bay', label: "Hangar", mass: 6, points: 18 },
  { kind: 'launch-tube', label: "Launch Tube", mass: 3, points: 9 },
  { kind: 'minesweeper', label: "Minesweeper", mass: 5, points: 15 },
  { kind: 'ortillery', label: "Ortillery", mass: 3, points: 9 },
  { kind: 'pds', label: "PDS", mass: 1, points: 3 },
  { kind: 'scattergun', label: "Scattergun", mass: 1, points: 5 },
  { kind: 'shipyard', label: "Shipyard", mass: 1, points: 2 },
  { kind: 'stealth-hull', label: "Stealth Hull", mass: 0, points: 2 },
  { kind: 'superior-sensors', label: "Sup Sensors", mass: 4, points: 16 },
  { kind: 'troop-berthing', label: "Troops", mass: 1, points: 0 },
]
