/**
 * What a designer may buy (14).
 *
 * GENERATED by tools/build_roster.py from the same section 14 tables the
 * roster is priced from — do not hand-edit. Emitting both from one source is
 * the point: a designer offering a cost the roster does not charge is how a
 * fleet quietly becomes unfair.
 *
 * Only flat-cost entries are here. Hulls, drives, FTL, streamlining and
 * screens are fractions of total ship mass and belong to designPricing.ts,
 * which computes them (13.7 - 13.11).
 */

import type { Arc, SystemKind, WeaponClass, WeaponVariant } from '../engine/types'

export interface CatalogueWeapon {
  weaponClass: WeaponClass
  variant: WeaponVariant
  rating: number
  label: string
  /** Arc counts this mounting is sold in, and what each costs (14.4). */
  mountings: ReadonlyArray<{ arcs: number; mass: number; points: number }>
  /**
   * Shots the mount is built with, for 6.6's crossed-off mountings — "Once
   * fired, it is crossed off and cannot be used again". Absent on everything
   * that reloads between turns, which is nearly everything.
   *
   * The Shipyard has to copy it onto a fitted weapon or a hand-built rack
   * fires for ever while the roster's identical rack does not.
   */
  ammo?: number
}

export interface CatalogueSystem {
  kind: SystemKind
  label: string
  mass: number
  points: number
}

/** Every arc, for a mounting sold at six. */
export const ALL_ARCS: readonly Arc[] = ['F', 'FS', 'AS', 'A', 'AP', 'FP']

export const CATALOGUE_WEAPONS: readonly CatalogueWeapon[] = [
  { weaponClass: 'beam', variant: 'standard', rating: 1, label: "Beam-1", mountings: [{ arcs: 6, mass: 1, points: 3 }] },
  { weaponClass: 'beam', variant: 'standard', rating: 2, label: "Beam-2", mountings: [{ arcs: 3, mass: 2, points: 6 }, { arcs: 6, mass: 3, points: 9 }] },
  { weaponClass: 'beam', variant: 'standard', rating: 3, label: "Beam-3", mountings: [{ arcs: 1, mass: 4, points: 12 }, { arcs: 2, mass: 5, points: 15 }, { arcs: 3, mass: 6, points: 18 }, { arcs: 4, mass: 7, points: 21 }, { arcs: 5, mass: 8, points: 24 }, { arcs: 6, mass: 9, points: 27 }] },
  { weaponClass: 'beam', variant: 'standard', rating: 4, label: "Beam-4", mountings: [{ arcs: 1, mass: 8, points: 24 }, { arcs: 2, mass: 10, points: 30 }, { arcs: 3, mass: 12, points: 36 }, { arcs: 4, mass: 14, points: 42 }, { arcs: 5, mass: 16, points: 48 }, { arcs: 6, mass: 18, points: 54 }] },
  { weaponClass: 'beam', variant: 'standard', rating: 5, label: "Beam-5", mountings: [{ arcs: 1, mass: 16, points: 48 }, { arcs: 2, mass: 20, points: 60 }, { arcs: 3, mass: 24, points: 72 }, { arcs: 4, mass: 28, points: 84 }, { arcs: 5, mass: 32, points: 96 }, { arcs: 6, mass: 36, points: 108 }] },
  { weaponClass: 'pulse-torpedo', variant: 'standard', rating: 1, label: "Pulse Torp", mountings: [{ arcs: 1, mass: 4, points: 12 }, { arcs: 2, mass: 5, points: 15 }, { arcs: 3, mass: 6, points: 18 }] },
  { weaponClass: 'pulse-torpedo', variant: 'short', rating: 1, label: "SR Pulse Torp", mountings: [{ arcs: 1, mass: 2, points: 6 }, { arcs: 3, mass: 3, points: 9 }] },
  { weaponClass: 'pulse-torpedo', variant: 'long', rating: 1, label: "LR Pulse Torp", mountings: [{ arcs: 1, mass: 8, points: 24 }, { arcs: 2, mass: 10, points: 30 }, { arcs: 3, mass: 12, points: 36 }] },
  { weaponClass: 'k-gun', variant: 'standard', rating: 1, label: "K-1", mountings: [{ arcs: 6, mass: 2, points: 8 }] },
  { weaponClass: 'k-gun', variant: 'standard', rating: 2, label: "K-2", mountings: [{ arcs: 1, mass: 3, points: 12 }, { arcs: 2, mass: 4, points: 16 }] },
  { weaponClass: 'k-gun', variant: 'standard', rating: 3, label: "K-3", mountings: [{ arcs: 1, mass: 5, points: 20 }] },
  { weaponClass: 'k-gun', variant: 'standard', rating: 4, label: "K-4", mountings: [{ arcs: 1, mass: 8, points: 32 }] },
  { weaponClass: 'heavy-missile', variant: 'standard', rating: 1, label: "Heavy Missile", mountings: [{ arcs: 3, mass: 2, points: 6 }], ammo: 1 },
  { weaponClass: 'heavy-missile', variant: 'extended', rating: 1, label: "ER Missile", mountings: [{ arcs: 3, mass: 3, points: 9 }], ammo: 1 },
  { weaponClass: 'salvo-missile-rack', variant: 'standard', rating: 1, label: "SM Rack", mountings: [{ arcs: 3, mass: 4, points: 12 }], ammo: 1 },
  { weaponClass: 'salvo-missile-launcher', variant: 'standard', rating: 1, label: "SML", mountings: [{ arcs: 3, mass: 3, points: 9 }] },
  { weaponClass: 'submunition-pack', variant: 'standard', rating: 1, label: "Submunition", mountings: [{ arcs: 3, mass: 1, points: 3 }] },
  { weaponClass: 'gatling', variant: 'standard', rating: 1, label: "Gatling", mountings: [{ arcs: 1, mass: 2, points: 8 }, { arcs: 3, mass: 3, points: 12 }, { arcs: 6, mass: 4, points: 16 }] },
  { weaponClass: 'needle-beam', variant: 'standard', rating: 1, label: "Needle-1", mountings: [{ arcs: 2, mass: 2, points: 6 }, { arcs: 3, mass: 3, points: 9 }] },
  { weaponClass: 'plasma-cannon', variant: 'standard', rating: 1, label: "Plasma-1", mountings: [{ arcs: 3, mass: 1, points: 3 }, { arcs: 6, mass: 2, points: 6 }] },
  { weaponClass: 'plasma-cannon', variant: 'standard', rating: 2, label: "Plasma-2", mountings: [{ arcs: 3, mass: 4, points: 12 }, { arcs: 6, mass: 6, points: 18 }] },
  { weaponClass: 'graser', variant: 'standard', rating: 1, label: "Graser-1", mountings: [{ arcs: 3, mass: 1, points: 3 }, { arcs: 6, mass: 2, points: 6 }] },
  { weaponClass: 'graser', variant: 'standard', rating: 2, label: "Graser-2", mountings: [{ arcs: 3, mass: 4, points: 12 }, { arcs: 6, mass: 6, points: 18 }] },
  { weaponClass: 'fusion-array', variant: 'standard', rating: 1, label: "Fusion Array", mountings: [{ arcs: 1, mass: 3, points: 9 }, { arcs: 2, mass: 4, points: 12 }, { arcs: 3, mass: 5, points: 15 }] },
  { weaponClass: 'pulser', variant: 'standard', rating: 1, label: "Pulser", mountings: [{ arcs: 1, mass: 2, points: 10 }, { arcs: 3, mass: 3, points: 15 }, { arcs: 6, mass: 4, points: 20 }] },
  { weaponClass: 'emp', variant: 'standard', rating: 1, label: "EMP-1", mountings: [{ arcs: 6, mass: 1, points: 3 }] },
  { weaponClass: 'emp', variant: 'standard', rating: 2, label: "EMP-2", mountings: [{ arcs: 3, mass: 2, points: 6 }, { arcs: 6, mass: 3, points: 9 }] },
  { weaponClass: 'emp', variant: 'standard', rating: 3, label: "EMP-3", mountings: [{ arcs: 1, mass: 4, points: 12 }, { arcs: 2, mass: 5, points: 15 }, { arcs: 3, mass: 6, points: 18 }, { arcs: 4, mass: 7, points: 21 }, { arcs: 5, mass: 8, points: 24 }, { arcs: 6, mass: 9, points: 27 }] },
  { weaponClass: 'emp', variant: 'standard', rating: 4, label: "EMP-4", mountings: [{ arcs: 1, mass: 8, points: 24 }, { arcs: 2, mass: 10, points: 30 }, { arcs: 3, mass: 12, points: 36 }, { arcs: 4, mass: 14, points: 42 }, { arcs: 5, mass: 16, points: 48 }, { arcs: 6, mass: 18, points: 54 }] },
  { weaponClass: 'heavy-graser', variant: 'standard', rating: 1, label: "Hvy Graser-1", mountings: [{ arcs: 1, mass: 2, points: 6 }, { arcs: 3, mass: 3, points: 9 }, { arcs: 6, mass: 4, points: 12 }] },
  { weaponClass: 'heavy-graser', variant: 'standard', rating: 2, label: "Hvy Graser-2", mountings: [{ arcs: 1, mass: 9, points: 27 }, { arcs: 2, mass: 12, points: 36 }, { arcs: 3, mass: 15, points: 45 }, { arcs: 6, mass: 24, points: 72 }] },
  { weaponClass: 'heavy-graser', variant: 'standard', rating: 3, label: "Hvy Graser-3", mountings: [{ arcs: 1, mass: 24, points: 72 }, { arcs: 2, mass: 30, points: 90 }, { arcs: 3, mass: 36, points: 108 }, { arcs: 6, mass: 54, points: 162 }] },
  { weaponClass: 'phaser', variant: 'standard', rating: 1, label: "Phaser-1", mountings: [{ arcs: 3, mass: 1, points: 5 }, { arcs: 6, mass: 2, points: 8 }] },
  { weaponClass: 'phaser', variant: 'standard', rating: 2, label: "Phaser-2", mountings: [{ arcs: 3, mass: 4, points: 14 }, { arcs: 6, mass: 6, points: 20 }] },
  { weaponClass: 'phaser', variant: 'standard', rating: 3, label: "Phaser-3", mountings: [{ arcs: 1, mass: 8, points: 26 }, { arcs: 2, mass: 10, points: 32 }, { arcs: 3, mass: 12, points: 38 }] },
  { weaponClass: 'phaser', variant: 'standard', rating: 4, label: "Phaser-4", mountings: [{ arcs: 1, mass: 16, points: 50 }, { arcs: 2, mass: 20, points: 62 }, { arcs: 3, mass: 24, points: 74 }] },
  { weaponClass: 'transporter', variant: 'standard', rating: 1, label: "Transporter-1", mountings: [{ arcs: 6, mass: 1, points: 3 }] },
  { weaponClass: 'transporter', variant: 'standard', rating: 2, label: "Transporter-2", mountings: [{ arcs: 3, mass: 2, points: 6 }, { arcs: 6, mass: 3, points: 9 }] },
  { weaponClass: 'transporter', variant: 'standard', rating: 3, label: "Transporter-3", mountings: [{ arcs: 1, mass: 4, points: 12 }, { arcs: 2, mass: 5, points: 15 }, { arcs: 3, mass: 6, points: 18 }, { arcs: 4, mass: 7, points: 21 }, { arcs: 5, mass: 8, points: 24 }, { arcs: 6, mass: 9, points: 27 }] },
  { weaponClass: 'transporter', variant: 'standard', rating: 4, label: "Transporter-4", mountings: [{ arcs: 1, mass: 8, points: 24 }, { arcs: 2, mass: 10, points: 30 }, { arcs: 3, mass: 12, points: 36 }, { arcs: 4, mass: 14, points: 42 }, { arcs: 5, mass: 16, points: 48 }, { arcs: 6, mass: 18, points: 54 }] },
  { weaponClass: 'twin-particle-array', variant: 'standard', rating: 1, label: "Twin Particle Array", mountings: [{ arcs: 1, mass: 2, points: 8 }, { arcs: 3, mass: 3, points: 12 }, { arcs: 6, mass: 4, points: 16 }] },
  { weaponClass: 'meson-projector', variant: 'standard', rating: 1, label: "Meson Projector", mountings: [{ arcs: 1, mass: 2, points: 8 }, { arcs: 3, mass: 3, points: 12 }, { arcs: 6, mass: 4, points: 16 }] },
  { weaponClass: 'gravitic-gun', variant: 'standard', rating: 1, label: "Grav-1", mountings: [{ arcs: 6, mass: 1, points: 3 }] },
  { weaponClass: 'gravitic-gun', variant: 'standard', rating: 2, label: "Grav-2", mountings: [{ arcs: 3, mass: 2, points: 6 }, { arcs: 6, mass: 3, points: 9 }] },
  { weaponClass: 'gravitic-gun', variant: 'standard', rating: 3, label: "Grav-3", mountings: [{ arcs: 1, mass: 4, points: 12 }, { arcs: 2, mass: 5, points: 15 }, { arcs: 3, mass: 6, points: 18 }, { arcs: 4, mass: 7, points: 21 }, { arcs: 5, mass: 8, points: 24 }, { arcs: 6, mass: 9, points: 27 }] },
  { weaponClass: 'k-gun', variant: 'standard', rating: 5, label: "K-5", mountings: [{ arcs: 1, mass: 11, points: 44 }] },
  { weaponClass: 'k-gun', variant: 'standard', rating: 6, label: "K-6", mountings: [{ arcs: 1, mass: 14, points: 56 }] },
  { weaponClass: 'k-gun', variant: 'short', rating: 1, label: "SRK-1", mountings: [{ arcs: 6, mass: 1.5, points: 6 }] },
  { weaponClass: 'k-gun', variant: 'short', rating: 2, label: "SRK-2", mountings: [{ arcs: 2, mass: 2, points: 8 }] },
  { weaponClass: 'k-gun', variant: 'short', rating: 3, label: "SRK-3", mountings: [{ arcs: 1, mass: 3, points: 12 }] },
  { weaponClass: 'k-gun', variant: 'short', rating: 4, label: "SRK-4", mountings: [{ arcs: 1, mass: 4, points: 16 }] },
  { weaponClass: 'k-gun', variant: 'short', rating: 5, label: "SRK-5", mountings: [{ arcs: 1, mass: 6, points: 24 }] },
  { weaponClass: 'k-gun', variant: 'short', rating: 6, label: "SRK-6", mountings: [{ arcs: 1, mass: 7, points: 28 }] },
  { weaponClass: 'k-gun', variant: 'long', rating: 1, label: "LRK-1", mountings: [{ arcs: 6, mass: 4, points: 16 }] },
  { weaponClass: 'k-gun', variant: 'long', rating: 2, label: "LRK-2", mountings: [{ arcs: 1, mass: 6, points: 24 }, { arcs: 2, mass: 8, points: 32 }] },
  { weaponClass: 'k-gun', variant: 'long', rating: 3, label: "LRK-3", mountings: [{ arcs: 1, mass: 10, points: 40 }] },
  { weaponClass: 'k-gun', variant: 'long', rating: 4, label: "LRK-4", mountings: [{ arcs: 1, mass: 16, points: 64 }] },
  { weaponClass: 'k-gun', variant: 'long', rating: 5, label: "LRK-5", mountings: [{ arcs: 1, mass: 22, points: 88 }] },
  { weaponClass: 'k-gun', variant: 'long', rating: 6, label: "LRK-6", mountings: [{ arcs: 1, mass: 28, points: 112 }] },
  { weaponClass: 'needle-beam', variant: 'standard', rating: 2, label: "Needle-2", mountings: [{ arcs: 1, mass: 4, points: 12 }, { arcs: 2, mass: 6, points: 18 }, { arcs: 3, mass: 8, points: 24 }] },
  { weaponClass: 'needle-beam', variant: 'standard', rating: 3, label: "Needle-3", mountings: [{ arcs: 1, mass: 8, points: 24 }, { arcs: 2, mass: 12, points: 36 }, { arcs: 3, mass: 16, points: 48 }] },
  { weaponClass: 'needle-beam', variant: 'standard', rating: 4, label: "Needle-4", mountings: [{ arcs: 1, mass: 16, points: 48 }, { arcs: 2, mass: 24, points: 72 }, { arcs: 3, mass: 32, points: 96 }] },
  { weaponClass: 'graser', variant: 'standard', rating: 3, label: "Graser-3", mountings: [{ arcs: 1, mass: 8, points: 24 }, { arcs: 2, mass: 10, points: 30 }, { arcs: 3, mass: 12, points: 36 }] },
  { weaponClass: 'graser', variant: 'standard', rating: 4, label: "Graser-4", mountings: [{ arcs: 1, mass: 16, points: 48 }, { arcs: 2, mass: 20, points: 60 }, { arcs: 3, mass: 24, points: 72 }] },
  { weaponClass: 'plasma-cannon', variant: 'standard', rating: 3, label: "Plasma-3", mountings: [{ arcs: 1, mass: 8, points: 24 }, { arcs: 2, mass: 10, points: 30 }, { arcs: 3, mass: 12, points: 36 }] },
  { weaponClass: 'plasma-cannon', variant: 'standard', rating: 4, label: "Plasma-4", mountings: [{ arcs: 1, mass: 16, points: 48 }, { arcs: 2, mass: 20, points: 60 }, { arcs: 3, mass: 24, points: 72 }] },
  { weaponClass: 'boarding-torpedo', variant: 'standard', rating: 1, label: "Boarding Torp", mountings: [{ arcs: 3, mass: 2, points: 6 }] },
  { weaponClass: 'mkp', variant: 'standard', rating: 1, label: "MKP", mountings: [{ arcs: 3, mass: 1, points: 4 }] },
  { weaponClass: 'antimatter-missile', variant: 'standard', rating: 1, label: "AM Missile", mountings: [{ arcs: 3, mass: 2, points: 10 }], ammo: 1 },
  { weaponClass: 'rocket-pod', variant: 'standard', rating: 1, label: "Rocket Pod", mountings: [{ arcs: 3, mass: 1, points: 3 }] },
  { weaponClass: 'mine-rack', variant: 'standard', rating: 1, label: "Mine Rack", mountings: [{ arcs: 3, mass: 2, points: 6 }] },
  { weaponClass: 'plasma-bolt-launcher', variant: 'standard', rating: 1, label: "PBL-1", mountings: [{ arcs: 1, mass: 3, points: 9 }, { arcs: 2, mass: 4, points: 12 }, { arcs: 3, mass: 5, points: 15 }] },
  { weaponClass: 'plasma-bolt-launcher', variant: 'standard', rating: 2, label: "PBL-2", mountings: [{ arcs: 1, mass: 6, points: 18 }, { arcs: 2, mass: 8, points: 24 }, { arcs: 3, mass: 10, points: 30 }] },
  { weaponClass: 'plasma-bolt-launcher', variant: 'standard', rating: 3, label: "PBL-3", mountings: [{ arcs: 1, mass: 9, points: 27 }, { arcs: 2, mass: 12, points: 36 }, { arcs: 3, mass: 15, points: 45 }] },
  { weaponClass: 'plasma-bolt-launcher', variant: 'standard', rating: 4, label: "PBL-4", mountings: [{ arcs: 1, mass: 12, points: 36 }, { arcs: 2, mass: 16, points: 48 }, { arcs: 3, mass: 20, points: 60 }] },
  { weaponClass: 'plasma-bolt-launcher', variant: 'standard', rating: 5, label: "PBL-5", mountings: [{ arcs: 1, mass: 15, points: 45 }, { arcs: 2, mass: 20, points: 60 }, { arcs: 3, mass: 25, points: 75 }] },
  { weaponClass: 'plasma-bolt-launcher', variant: 'standard', rating: 6, label: "PBL-6", mountings: [{ arcs: 1, mass: 18, points: 54 }, { arcs: 2, mass: 24, points: 72 }, { arcs: 3, mass: 30, points: 90 }] },
  { weaponClass: 'spinal-beam', variant: 'standard', rating: 1, label: "Spinal Beam-1", mountings: [{ arcs: 1, mass: 8, points: 32 }] },
  { weaponClass: 'spinal-beam', variant: 'standard', rating: 2, label: "Spinal Beam-2", mountings: [{ arcs: 1, mass: 16, points: 64 }] },
  { weaponClass: 'spinal-beam', variant: 'standard', rating: 3, label: "Spinal Beam-3", mountings: [{ arcs: 1, mass: 32, points: 128 }] },
  { weaponClass: 'spinal-plasma', variant: 'standard', rating: 1, label: "Spinal Plasma-1", mountings: [{ arcs: 1, mass: 8, points: 32 }] },
  { weaponClass: 'spinal-plasma', variant: 'standard', rating: 2, label: "Spinal Plasma-2", mountings: [{ arcs: 1, mass: 16, points: 64 }] },
  { weaponClass: 'spinal-plasma', variant: 'standard', rating: 3, label: "Spinal Plasma-3", mountings: [{ arcs: 1, mass: 32, points: 128 }] },
  { weaponClass: 'spinal-psp', variant: 'standard', rating: 1, label: "Spinal PSP-1", mountings: [{ arcs: 1, mass: 8, points: 40 }] },
  { weaponClass: 'spinal-psp', variant: 'standard', rating: 2, label: "Spinal PSP-2", mountings: [{ arcs: 1, mass: 16, points: 80 }] },
  { weaponClass: 'spinal-psp', variant: 'standard', rating: 3, label: "Spinal PSP-3", mountings: [{ arcs: 1, mass: 32, points: 160 }] },
  { weaponClass: 'nova-cannon', variant: 'standard', rating: 1, label: "Nova Cannon", mountings: [{ arcs: 1, mass: 20, points: 60 }] },
  { weaponClass: 'wave-gun', variant: 'standard', rating: 1, label: "Wave Gun", mountings: [{ arcs: 1, mass: 12, points: 36 }] },
]

export const CATALOGUE_SYSTEMS: readonly CatalogueSystem[] = [
  { kind: 'adfc', label: "ADFC", mass: 2, points: 8 },
  { kind: 'ads', label: "ADS", mass: 2, points: 6 },
  { kind: 'ads', label: "ADS", mass: 3, points: 9 },
  { kind: 'advanced-adfc', label: "Adv ADFC", mass: 2, points: 10 },
  { kind: 'advanced-firecon', label: "Adv FireCon", mass: 1, points: 5 },
  { kind: 'antimatter-charge', label: "AM Charge", mass: 1, points: 5 },
  { kind: 'area-ecm', label: "Area ECM", mass: 2, points: 6 },
  { kind: 'boat-bay', label: "Boat Bay", mass: 1.5, points: 0 },
  { kind: 'cargo', label: "Cargo", mass: 1, points: 0 },
  { kind: 'catapult', label: "Catapult", mass: 1, points: 0 },
  { kind: 'cloaking-device', label: "Cloaking Device", mass: 1, points: 0 },
  { kind: 'cloaking-field', label: "Cloaking Field", mass: 1, points: 0 },
  { kind: 'ecm', label: "ECM", mass: 1, points: 3 },
  { kind: 'enhanced-sensors', label: "Enh Sensors", mass: 2, points: 8 },
  { kind: 'firecon', label: "FireCon", mass: 1, points: 4 },
  { kind: 'grapeshot', label: "Grapeshot", mass: 1, points: 4 },
  { kind: 'gunboat-bay', label: "Gunboat Bay", mass: 24, points: 0 },
  { kind: 'gunboat-rack', label: "Gunboat Rack", mass: 18, points: 0 },
  { kind: 'hangar-bay', label: "Hangar", mass: 6, points: 18 },
  { kind: 'holofield', label: "Holofield", mass: 0, points: 0 },
  { kind: 'launch-tube', label: "Launch Tube", mass: 3, points: 9 },
  { kind: 'minesweeper', label: "Minesweeper", mass: 5, points: 15 },
  { kind: 'ortillery', label: "Ortillery", mass: 3, points: 9 },
  { kind: 'pds', label: "PDS", mass: 1, points: 3 },
  { kind: 'reflex-field', label: "Reflex Field", mass: 0, points: 0 },
  { kind: 'scattergun', label: "Scattergun", mass: 1, points: 5 },
  { kind: 'shipyard', label: "Shipyard", mass: 1, points: 2 },
  { kind: 'stealth-field', label: "Stealth Field", mass: 0, points: 0 },
  { kind: 'stealth-hull', label: "Stealth Hull", mass: 0, points: 0 },
  { kind: 'superior-sensors', label: "Sup Sensors", mass: 4, points: 16 },
  { kind: 'tender', label: "Ship Bay", mass: 1.5, points: 4.5 },
  { kind: 'troop-berthing', label: "Troops", mass: 1, points: 0 },
  { kind: 'tuffley-cloak', label: "Tuffley Cloak", mass: 0, points: 0 },
  { kind: 'weasel-emitter', label: "Weasel Emitter", mass: 2, points: 8 },
]
